/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2CHANNELSTATUSTABLE_H
#define XDSL2CHANNELSTATUSTABLE_H

/* function declarations */
void init_xdsl2ChannelStatusTable(void);
void initialize_table_xdsl2ChannelStatusTable(void);
Netsnmp_Node_Handler xdsl2ChannelStatusTable_handler;
Netsnmp_First_Data_Point  xdsl2ChannelStatusTable_get_first_data_point;
static void populate_xdsl2ChannelStatusTable(void);
Netsnmp_Next_Data_Point   xdsl2ChannelStatusTable_get_next_data_point;

/* column number definitions for table xdsl2ChannelStatusTable */
       #define COLUMN_XDSL2CHSTATUSUNIT		1
       #define COLUMN_XDSL2CHSTATUSACTDATARATE		2
       #define COLUMN_XDSL2CHSTATUSPREVDATARATE		3
       #define COLUMN_XDSL2CHSTATUSACTDELAY		4
       #define COLUMN_XDSL2CHSTATUSACTINP		5
       #define COLUMN_XDSL2CHSTATUSINPREPORT		6
       #define COLUMN_XDSL2CHSTATUSNFEC		7
       #define COLUMN_XDSL2CHSTATUSRFEC		8
       #define COLUMN_XDSL2CHSTATUSLSYMB		9
       #define COLUMN_XDSL2CHSTATUSINTLVDEPTH		10
       #define COLUMN_XDSL2CHSTATUSINTLVBLOCK		11
       #define COLUMN_XDSL2CHSTATUSLPATH		12
       #define COLUMN_XDSL2CHSTATUSATMSTATUS		13
       #define COLUMN_XDSL2CHSTATUSPTMSTATUS		14
#endif /* XDSL2CHANNELSTATUSTABLE_H */
