/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2ChannelStatusTable.h"
#include "xdslctl_output_parser.h"

/** Initializes the xdsl2ChannelStatusTable module */
void
init_xdsl2ChannelStatusTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2ChannelStatusTable();
}


/** Initialize the xdsl2ChannelStatusTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2ChannelStatusTable(void)
{
    const oid xdsl2ChannelStatusTable_oid[] = {1,3,6,1,2,1,10,251,1,2,2};
    const size_t xdsl2ChannelStatusTable_oid_len   = OID_LENGTH(xdsl2ChannelStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2ChannelStatusTable:init", "initializing table xdsl2ChannelStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2ChannelStatusTable",     xdsl2ChannelStatusTable_handler,
              xdsl2ChannelStatusTable_oid, xdsl2ChannelStatusTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2ChStatusUnit */
                           0);
    table_info->min_column = COLUMN_XDSL2CHSTATUSACTDATARATE;
    table_info->max_column = COLUMN_XDSL2CHSTATUSPTMSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2ChannelStatusTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2ChannelStatusTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2ChannelStatusTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2ChStatusUnit;

    /* Column values */
    uint32_t xdsl2ChStatusActDataRate;
    uint32_t xdsl2ChStatusPrevDataRate;
    uint16_t xdsl2ChStatusActDelay;
    uint8_t xdsl2ChStatusActInp;
    long xdsl2ChStatusInpReport;
    uint8_t xdsl2ChStatusNFec;
    uint8_t xdsl2ChStatusRFec;
    uint16_t xdsl2ChStatusLSymb;
    uint16_t xdsl2ChStatusIntlvDepth;
    uint8_t xdsl2ChStatusIntlvBlock;
    uint8_t xdsl2ChStatusLPath;
    unsigned char xdsl2ChStatusAtmStatus;
    unsigned char xdsl2ChStatusPtmStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2ChannelStatusTable_entry *next;
};

struct xdsl2ChannelStatusTable_entry  *xdsl2ChannelStatusTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2ChannelStatusTable_entry *
xdsl2ChannelStatusTable_createEntry(long ifIndex, long xdsl2ChStatusUnit) {
    struct xdsl2ChannelStatusTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2ChannelStatusTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2ChStatusUnit = xdsl2ChStatusUnit;
    entry->next = xdsl2ChannelStatusTable_head;
    xdsl2ChannelStatusTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2ChannelStatusTable_removeEntry( struct xdsl2ChannelStatusTable_entry *entry ) {
    struct xdsl2ChannelStatusTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2ChannelStatusTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2ChannelStatusTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2ChannelStatusTable_get_first_data_point(void **my_loop_context, void **my_data_context, netsnmp_variable_list *put_index_data, netsnmp_iterator_info *mydata)
{
    populate_xdsl2ChannelStatusTable();

    *my_loop_context = xdsl2ChannelStatusTable_head;
    return xdsl2ChannelStatusTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

static void populate_xdsl2ChannelStatusTable(void)
{
    struct xdsl2ChannelStatusTable_entry* entry;

    // Free old list if needed
    while (xdsl2ChannelStatusTable_head) {
        entry = xdsl2ChannelStatusTable_head;
        xdsl2ChannelStatusTable_head = entry->next;
        free(entry);
    }

    xdsl_stats_t lines_stats[MAX_XDSL_LINES];
    uint8_t known_lines = get_xdslctl_stats(lines_stats, MAX_XDSL_LINES);
    for (int8_t linenum = known_lines - 1; linenum >= 0; linenum--) {
        DEBUGMSGTL(("xdsl2ChannelStatusTable:populate", "Line %d, Bearer 0 up=%u down=%u\n", linenum, lines_stats[linenum].bearer[0].up_rate_kbps, lines_stats[linenum].bearer[0].down_rate_kbps));
        for (xdsl_termination_unit_t tu = xtuc; tu <= xtur; tu++) { // 1 channel per termination unit
            entry = xdsl2ChannelStatusTable_createEntry(linenum + BASE_IFINDEX, tu);
            if (tu == xtur) {
                // Ignore 2nd bearer.
                entry->xdsl2ChStatusActDataRate = lines_stats[linenum].bearer[0].down_rate_kbps * 1000;
                entry->xdsl2ChStatusActDelay = lines_stats[linenum].bearer[0].delay[0];
            }
            else if (tu == xtuc) {
                entry->xdsl2ChStatusActDataRate = lines_stats[linenum].bearer[0].up_rate_kbps * 1000;
                entry->xdsl2ChStatusActDelay = lines_stats[linenum].bearer[0].delay[1];
            }
        }
    }
}

netsnmp_variable_list *
xdsl2ChannelStatusTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2ChannelStatusTable_entry *entry = (struct xdsl2ChannelStatusTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2ChStatusUnit );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2ChannelStatusTable table */
int
xdsl2ChannelStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2ChannelStatusTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2ChannelStatusTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2ChannelStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2CHSTATUSACTDATARATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusActDataRate);
                break;
            case COLUMN_XDSL2CHSTATUSPREVDATARATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusPrevDataRate);
                break;
            case COLUMN_XDSL2CHSTATUSACTDELAY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusActDelay);
                break;
            case COLUMN_XDSL2CHSTATUSACTINP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusActInp);
                break;
            case COLUMN_XDSL2CHSTATUSINPREPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2ChStatusInpReport);
                break;
            case COLUMN_XDSL2CHSTATUSNFEC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusNFec);
                break;
            case COLUMN_XDSL2CHSTATUSRFEC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusRFec);
                break;
            case COLUMN_XDSL2CHSTATUSLSYMB:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusLSymb);
                break;
            case COLUMN_XDSL2CHSTATUSINTLVDEPTH:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusIntlvDepth);
                break;
            case COLUMN_XDSL2CHSTATUSINTLVBLOCK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusIntlvBlock);
                break;
            case COLUMN_XDSL2CHSTATUSLPATH:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2ChStatusLPath);
                break;
            case COLUMN_XDSL2CHSTATUSATMSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR, &table_entry->xdsl2ChStatusAtmStatus, sizeof(table_entry->xdsl2ChStatusAtmStatus));
                break;
            case COLUMN_XDSL2CHSTATUSPTMSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR, &table_entry->xdsl2ChStatusPtmStatus, sizeof(table_entry->xdsl2ChStatusPtmStatus));
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
