/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMLINEINITHIST1DAYTABLE_H
#define XDSL2PMLINEINITHIST1DAYTABLE_H

/* function declarations */
void init_xdsl2PMLineInitHist1DayTable(void);
void initialize_table_xdsl2PMLineInitHist1DayTable(void);
Netsnmp_Node_Handler xdsl2PMLineInitHist1DayTable_handler;
Netsnmp_First_Data_Point  xdsl2PMLineInitHist1DayTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMLineInitHist1DayTable_get_next_data_point;

/* column number definitions for table xdsl2PMLineInitHist1DayTable */
       #define COLUMN_XDSL2PMLINITHIST1DINTERVAL		1
       #define COLUMN_XDSL2PMLINITHIST1DMONITOREDTIME		2
       #define COLUMN_XDSL2PMLINITHIST1DFULLINITS		3
       #define COLUMN_XDSL2PMLINITHIST1DFAILEDFULLINITS		4
       #define COLUMN_XDSL2PMLINITHIST1DSHORTINITS		5
       #define COLUMN_XDSL2PMLINITHIST1DFAILEDSHORTINITS		6
       #define COLUMN_XDSL2PMLINITHIST1DVALIDINTERVAL		7
#endif /* XDSL2PMLINEINITHIST1DAYTABLE_H */
