/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMLINECURRTABLE_H
#define XDSL2PMLINECURRTABLE_H

/* function declarations */
void init_xdsl2PMLineCurrTable(void);
void initialize_table_xdsl2PMLineCurrTable(void);
Netsnmp_Node_Handler xdsl2PMLineCurrTable_handler;
Netsnmp_First_Data_Point  xdsl2PMLineCurrTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMLineCurrTable_get_next_data_point;

/* column number definitions for table xdsl2PMLineCurrTable */
       #define COLUMN_XDSL2PMLCURRUNIT		1
       #define COLUMN_XDSL2PMLCURR15MVALIDINTERVALS		2
       #define COLUMN_XDSL2PMLCURR15MINVALIDINTERVALS		3
       #define COLUMN_XDSL2PMLCURR15MTIMEELAPSED		4
       #define COLUMN_XDSL2PMLCURR15MFECS		5
       #define COLUMN_XDSL2PMLCURR15MES		6
       #define COLUMN_XDSL2PMLCURR15MSES		7
       #define COLUMN_XDSL2PMLCURR15MLOSS		8
       #define COLUMN_XDSL2PMLCURR15MUAS		9
       #define COLUMN_XDSL2PMLCURR1DAYVALIDINTERVALS		10
       #define COLUMN_XDSL2PMLCURR1DAYINVALIDINTERVALS		11
       #define COLUMN_XDSL2PMLCURR1DAYTIMEELAPSED		12
       #define COLUMN_XDSL2PMLCURR1DAYFECS		13
       #define COLUMN_XDSL2PMLCURR1DAYES		14
       #define COLUMN_XDSL2PMLCURR1DAYSES		15
       #define COLUMN_XDSL2PMLCURR1DAYLOSS		16
       #define COLUMN_XDSL2PMLCURR1DAYUAS		17
#endif /* XDSL2PMLINECURRTABLE_H */
