/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2SCStatusSegmentTable.h"

/** Initializes the xdsl2SCStatusSegmentTable module */
void
init_xdsl2SCStatusSegmentTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2SCStatusSegmentTable();
}


/** Initialize the xdsl2SCStatusSegmentTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2SCStatusSegmentTable(void)
{
    const oid xdsl2SCStatusSegmentTable_oid[] = {1,3,6,1,2,1,10,251,1,2,5};
    const size_t xdsl2SCStatusSegmentTable_oid_len   = OID_LENGTH(xdsl2SCStatusSegmentTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2SCStatusSegmentTable:init", "initializing table xdsl2SCStatusSegmentTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2SCStatusSegmentTable",     xdsl2SCStatusSegmentTable_handler,
              xdsl2SCStatusSegmentTable_oid, xdsl2SCStatusSegmentTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2SCStatusDirection */
                           ASN_UNSIGNED,  /* index: xdsl2SCStatusSegment */
                           0);
    table_info->min_column = COLUMN_XDSL2SCSTATUSSEGMENTLINREAL;
    table_info->max_column = COLUMN_XDSL2SCSTATUSSEGMENTGAINALLOC;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2SCStatusSegmentTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2SCStatusSegmentTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2SCStatusSegmentTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2SCStatusDirection;
    u_long xdsl2SCStatusSegment;

    /* Column values */
    char xdsl2SCStatusSegmentLinReal[MAX_LEN_1024];
    size_t xdsl2SCStatusSegmentLinReal_len;
    char xdsl2SCStatusSegmentLinImg[MAX_LEN_1024];
    size_t xdsl2SCStatusSegmentLinImg_len;
    char xdsl2SCStatusSegmentLog[MAX_LEN_1024];
    size_t xdsl2SCStatusSegmentLog_len;
    char xdsl2SCStatusSegmentQln[MAX_LEN_512];
    size_t xdsl2SCStatusSegmentQln_len;
    char xdsl2SCStatusSegmentSnr[MAX_LEN_512];
    size_t xdsl2SCStatusSegmentSnr_len;
    char xdsl2SCStatusSegmentBitsAlloc[MAX_LEN_32];
    size_t xdsl2SCStatusSegmentBitsAlloc_len;
    char xdsl2SCStatusSegmentGainAlloc[MAX_LEN_1024];
    size_t xdsl2SCStatusSegmentGainAlloc_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2SCStatusSegmentTable_entry *next;
};

struct xdsl2SCStatusSegmentTable_entry  *xdsl2SCStatusSegmentTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2SCStatusSegmentTable_entry *
xdsl2SCStatusSegmentTable_createEntry(long ifIndex, long xdsl2SCStatusDirection, u_long xdsl2SCStatusSegment) {
    struct xdsl2SCStatusSegmentTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2SCStatusSegmentTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2SCStatusDirection = xdsl2SCStatusDirection;
    entry->xdsl2SCStatusSegment = xdsl2SCStatusSegment;
    entry->next = xdsl2SCStatusSegmentTable_head;
    xdsl2SCStatusSegmentTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2SCStatusSegmentTable_removeEntry( struct xdsl2SCStatusSegmentTable_entry *entry ) {
    struct xdsl2SCStatusSegmentTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2SCStatusSegmentTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2SCStatusSegmentTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2SCStatusSegmentTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2SCStatusSegmentTable_head;
    return xdsl2SCStatusSegmentTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2SCStatusSegmentTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2SCStatusSegmentTable_entry *entry = (struct xdsl2SCStatusSegmentTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2SCStatusDirection );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->xdsl2SCStatusSegment );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2SCStatusSegmentTable table */
int
xdsl2SCStatusSegmentTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2SCStatusSegmentTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2SCStatusSegmentTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2SCStatusSegmentTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2SCSTATUSSEGMENTLINREAL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentLinReal,
                                          table_entry->xdsl2SCStatusSegmentLinReal_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTLINIMG:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentLinImg,
                                          table_entry->xdsl2SCStatusSegmentLinImg_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTLOG:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentLog,
                                          table_entry->xdsl2SCStatusSegmentLog_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTQLN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentQln,
                                          table_entry->xdsl2SCStatusSegmentQln_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTSNR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentSnr,
                                          table_entry->xdsl2SCStatusSegmentSnr_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTBITSALLOC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentBitsAlloc,
                                          table_entry->xdsl2SCStatusSegmentBitsAlloc_len);
                break;
            case COLUMN_XDSL2SCSTATUSSEGMENTGAINALLOC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->xdsl2SCStatusSegmentGainAlloc,
                                          table_entry->xdsl2SCStatusSegmentGainAlloc_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
