/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINECONFPROFMODESPECTABLE_H
#define XDSL2LINECONFPROFMODESPECTABLE_H

#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineConfProfModeSpecTable(void);
void initialize_table_xdsl2LineConfProfModeSpecTable(void);
Netsnmp_Node_Handler xdsl2LineConfProfModeSpecTable_handler;
Netsnmp_First_Data_Point  xdsl2LineConfProfModeSpecTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineConfProfModeSpecTable_get_next_data_point;

/* column number definitions for table xdsl2LineConfProfModeSpecTable */
       #define COLUMN_XDSL2LCONFPROFXDSLMODE		1
       #define COLUMN_XDSL2LCONFPROFMAXNOMPSDDS		2
       #define COLUMN_XDSL2LCONFPROFMAXNOMPSDUS		3
       #define COLUMN_XDSL2LCONFPROFMAXNOMATPDS		4
       #define COLUMN_XDSL2LCONFPROFMAXNOMATPUS		5
       #define COLUMN_XDSL2LCONFPROFMAXAGGRXPWRUS		6
       #define COLUMN_XDSL2LCONFPROFPSDMASKDS		7
       #define COLUMN_XDSL2LCONFPROFPSDMASKUS		8
       #define COLUMN_XDSL2LCONFPROFPSDMASKSELECTUS		9
       #define COLUMN_XDSL2LCONFPROFCLASSMASK		10
       #define COLUMN_XDSL2LCONFPROFLIMITMASK		11
       #define COLUMN_XDSL2LCONFPROFUS0DISABLE		12
       #define COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS		13
#endif /* XDSL2LINECONFPROFMODESPECTABLE_H */
