/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINESEGMENTTABLE_H
#define XDSL2LINESEGMENTTABLE_H

#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineSegmentTable(void);
void initialize_table_xdsl2LineSegmentTable(void);
Netsnmp_Node_Handler xdsl2LineSegmentTable_handler;
Netsnmp_First_Data_Point  xdsl2LineSegmentTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineSegmentTable_get_next_data_point;

/* column number definitions for table xdsl2LineSegmentTable */
       #define COLUMN_XDSL2LINESEGMENTDIRECTION		1
       #define COLUMN_XDSL2LINESEGMENT		2
       #define COLUMN_XDSL2LINESEGMENTBITSALLOC		3
       #define COLUMN_XDSL2LINESEGMENTROWSTATUS		4
#endif /* XDSL2LINESEGMENTTABLE_H */
