/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINECONFPROFMODESPECBANDUSTABLE_H
#define XDSL2LINECONFPROFMODESPECBANDUSTABLE_H

#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineConfProfModeSpecBandUsTable(void);
void initialize_table_xdsl2LineConfProfModeSpecBandUsTable(void);
Netsnmp_Node_Handler xdsl2LineConfProfModeSpecBandUsTable_handler;
Netsnmp_First_Data_Point  xdsl2LineConfProfModeSpecBandUsTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineConfProfModeSpecBandUsTable_get_next_data_point;

/* column number definitions for table xdsl2LineConfProfModeSpecBandUsTable */
       #define COLUMN_XDSL2LCONFPROFXDSLBANDUS		1
       #define COLUMN_XDSL2LCONFPROFUPBOPSDA		2
       #define COLUMN_XDSL2LCONFPROFUPBOPSDB		3
       #define COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS		4
#endif /* XDSL2LINECONFPROFMODESPECBANDUSTABLE_H */
