/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineInventoryTable.h"
#include "xdslctl_output_parser.h"

/** Initializes the xdsl2LineInventoryTable module */
void
init_xdsl2LineInventoryTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2LineInventoryTable();
}


/** Initialize the xdsl2LineInventoryTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineInventoryTable(void)
{
    const oid xdsl2LineInventoryTable_oid[] = {1,3,6,1,2,1,10,251,1,3,1};
    const size_t xdsl2LineInventoryTable_oid_len   = OID_LENGTH(xdsl2LineInventoryTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2LineInventoryTable:init", "initializing table xdsl2LineInventoryTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2LineInventoryTable",     xdsl2LineInventoryTable_handler,
              xdsl2LineInventoryTable_oid, xdsl2LineInventoryTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2LInvUnit */
                           0);
    table_info->min_column = COLUMN_XDSL2LINVG994VENDORID;
    table_info->max_column = COLUMN_XDSL2LINVTRANSMISSIONCAPABILITIES;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2LineInventoryTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2LineInventoryTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2LineInventoryTable_entry {
    /* Index values */
    long ifIndex;
    uint8_t xdsl2LInvUnit;

    /* Column values */
    char xdsl2LInvG994VendorId[MAX_LEN_8];
    char xdsl2LInvSystemVendorId[MAX_LEN_8];
    char xdsl2LInvVersionNumber[MAX_LEN_16];
    char xdsl2LInvSerialNumber[MAX_LEN_32];
    unsigned int xdsl2LInvSelfTestResult;
    char xdsl2LInvTransmissionCapabilities[MAX_LEN_8];
    size_t xdsl2LInvTransmissionCapabilities_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2LineInventoryTable_entry *next;
};

struct xdsl2LineInventoryTable_entry  *xdsl2LineInventoryTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineInventoryTable_entry *
xdsl2LineInventoryTable_createEntry(long ifIndex, long xdsl2LInvUnit) {
    struct xdsl2LineInventoryTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineInventoryTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2LInvUnit = xdsl2LInvUnit;
    entry->next = xdsl2LineInventoryTable_head;
    xdsl2LineInventoryTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2LineInventoryTable_removeEntry( struct xdsl2LineInventoryTable_entry *entry ) {
    struct xdsl2LineInventoryTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2LineInventoryTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2LineInventoryTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2LineInventoryTable_get_first_data_point(void **my_loop_context, void **my_data_context, netsnmp_variable_list *put_index_data, netsnmp_iterator_info *mydata)
{
    populate_xdsl2LineInventoryTable();

    *my_loop_context = xdsl2LineInventoryTable_head;
    return xdsl2LineInventoryTable_get_next_data_point(my_loop_context, my_data_context, put_index_data, mydata );
}

static void populate_xdsl2LineInventoryTable(void)
{
    struct xdsl2LineInventoryTable_entry* entry;

    // Free old list if needed
    while (xdsl2LineInventoryTable_head) {
        entry = xdsl2LineInventoryTable_head;
        xdsl2LineInventoryTable_head = entry->next;
        free(entry);
    }

    xdsl_stats_t lines_stats[MAX_XDSL_LINES];
    xdsl_vendor_info_t vendor_info;
    uint8_t known_lines = get_xdslctl_stats(lines_stats, MAX_XDSL_LINES);
    if (get_xdslctl_vendor_info(&vendor_info) == 0) {
        for (int8_t linenum = known_lines - 1; linenum >= 0; linenum--) {
            entry = xdsl2LineInventoryTable_createEntry(linenum + BASE_IFINDEX, xtur); // XTUR assumed, don't know if it can be known from xdslctl
            strncpy(entry->xdsl2LInvG994VendorId, vendor_info.xdsl2LInvG994VendorId, sizeof(vendor_info.xdsl2LInvG994VendorId));
            strncpy(entry->xdsl2LInvSerialNumber, vendor_info.xdsl2LInvSerialNumber, sizeof(vendor_info.xdsl2LInvSerialNumber));
            strncpy(entry->xdsl2LInvSystemVendorId, vendor_info.xdsl2LInvSystemVendorId, sizeof(vendor_info.xdsl2LInvSystemVendorId));
            strncpy(entry->xdsl2LInvVersionNumber, vendor_info.xdsl2LInvVersionNumber, sizeof(vendor_info.xdsl2LInvVersionNumber));
        }
    }
}

netsnmp_variable_list *
xdsl2LineInventoryTable_get_next_data_point(void **my_loop_context, void **my_data_context, netsnmp_variable_list *put_index_data, netsnmp_iterator_info *mydata)
{
    struct xdsl2LineInventoryTable_entry *entry = (struct xdsl2LineInventoryTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2LInvUnit );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2LineInventoryTable table */
int
xdsl2LineInventoryTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2LineInventoryTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2LineInventoryTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2LineInventoryTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2LINVG994VENDORID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR, table_entry->xdsl2LInvG994VendorId, strlen(table_entry->xdsl2LInvG994VendorId));
                break;
            case COLUMN_XDSL2LINVSYSTEMVENDORID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR, table_entry->xdsl2LInvSystemVendorId, strlen(table_entry->xdsl2LInvSystemVendorId));
                break;
            case COLUMN_XDSL2LINVVERSIONNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR, table_entry->xdsl2LInvVersionNumber, strlen(table_entry->xdsl2LInvVersionNumber));
                break;
            case COLUMN_XDSL2LINVSERIALNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR, table_entry->xdsl2LInvSerialNumber, strlen(table_entry->xdsl2LInvSerialNumber));
                break;
            case COLUMN_XDSL2LINVSELFTESTRESULT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2LInvSelfTestResult);
                break;
            case COLUMN_XDSL2LINVTRANSMISSIONCAPABILITIES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR, table_entry->xdsl2LInvTransmissionCapabilities, table_entry->xdsl2LInvTransmissionCapabilities_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
