/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineConfProfTable.h"

 /** Initializes the xdsl2LineConfProfTable module */
void
init_xdsl2LineConfProfTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineConfProfTable();
}


/** Initialize the xdsl2LineConfProfTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineConfProfTable(void)
{
	const oid xdsl2LineConfProfTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,1,2 };
	const size_t xdsl2LineConfProfTable_oid_len = OID_LENGTH(xdsl2LineConfProfTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineConfProfTable:init", "initializing table xdsl2LineConfProfTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineConfProfTable", xdsl2LineConfProfTable_handler,
		xdsl2LineConfProfTable_oid, xdsl2LineConfProfTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LConfProfProfileName */
		0);
	table_info->min_column = COLUMN_XDSL2LCONFPROFSCMASKDS;
	table_info->max_column = COLUMN_XDSL2LCONFPROFROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineConfProfTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineConfProfTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineConfProfTable_entry {
	/* Index values */
	char xdsl2LConfProfProfileName[MAX_LEN_32];
	size_t xdsl2LConfProfProfileName_len;

	/* Column values */
	char xdsl2LConfProfScMaskDs[MAX_LEN_512];
	size_t xdsl2LConfProfScMaskDs_len;
	char old_xdsl2LConfProfScMaskDs[MAX_LEN_512];
	size_t old_xdsl2LConfProfScMaskDs_len;
	char xdsl2LConfProfScMaskUs[MAX_LEN_512];
	size_t xdsl2LConfProfScMaskUs_len;
	char old_xdsl2LConfProfScMaskUs[MAX_LEN_512];
	size_t old_xdsl2LConfProfScMaskUs_len;
	char xdsl2LConfProfVdsl2CarMask[MAX_LEN_512];
	size_t xdsl2LConfProfVdsl2CarMask_len;
	char old_xdsl2LConfProfVdsl2CarMask[MAX_LEN_512];
	size_t old_xdsl2LConfProfVdsl2CarMask_len;
	char xdsl2LConfProfRfiBands[MAX_LEN_512];
	size_t xdsl2LConfProfRfiBands_len;
	char old_xdsl2LConfProfRfiBands[MAX_LEN_512];
	size_t old_xdsl2LConfProfRfiBands_len;
	long xdsl2LConfProfRaModeDs;
	long old_xdsl2LConfProfRaModeDs;
	long xdsl2LConfProfRaModeUs;
	long old_xdsl2LConfProfRaModeUs;
	u_long xdsl2LConfProfRaUsNrmDs;
	u_long old_xdsl2LConfProfRaUsNrmDs;
	u_long xdsl2LConfProfRaUsNrmUs;
	u_long old_xdsl2LConfProfRaUsNrmUs;
	u_long xdsl2LConfProfRaUsTimeDs;
	u_long old_xdsl2LConfProfRaUsTimeDs;
	u_long xdsl2LConfProfRaUsTimeUs;
	u_long old_xdsl2LConfProfRaUsTimeUs;
	u_long xdsl2LConfProfRaDsNrmDs;
	u_long old_xdsl2LConfProfRaDsNrmDs;
	u_long xdsl2LConfProfRaDsNrmUs;
	u_long old_xdsl2LConfProfRaDsNrmUs;
	u_long xdsl2LConfProfRaDsTimeDs;
	u_long old_xdsl2LConfProfRaDsTimeDs;
	u_long xdsl2LConfProfRaDsTimeUs;
	u_long old_xdsl2LConfProfRaDsTimeUs;
	u_long xdsl2LConfProfTargetSnrmDs;
	u_long old_xdsl2LConfProfTargetSnrmDs;
	u_long xdsl2LConfProfTargetSnrmUs;
	u_long old_xdsl2LConfProfTargetSnrmUs;
	u_long xdsl2LConfProfMaxSnrmDs;
	u_long old_xdsl2LConfProfMaxSnrmDs;
	u_long xdsl2LConfProfMaxSnrmUs;
	u_long old_xdsl2LConfProfMaxSnrmUs;
	u_long xdsl2LConfProfMinSnrmDs;
	u_long old_xdsl2LConfProfMinSnrmDs;
	u_long xdsl2LConfProfMinSnrmUs;
	u_long old_xdsl2LConfProfMinSnrmUs;
	u_long xdsl2LConfProfMsgMinUs;
	u_long old_xdsl2LConfProfMsgMinUs;
	u_long xdsl2LConfProfMsgMinDs;
	u_long old_xdsl2LConfProfMsgMinDs;
	uint8_t xdsl2LConfProfCeFlag;
	uint8_t old_xdsl2LConfProfCeFlag;
	ulong xdsl2LConfProfSnrModeDs;
	ulong old_xdsl2LConfProfSnrModeDs;
	ulong xdsl2LConfProfSnrModeUs;
	ulong old_xdsl2LConfProfSnrModeUs;
	char xdsl2LConfProfTxRefVnDs[MAX_LEN_512];
	size_t xdsl2LConfProfTxRefVnDs_len;
	char old_xdsl2LConfProfTxRefVnDs[MAX_LEN_512];
	size_t old_xdsl2LConfProfTxRefVnDs_len;
	char xdsl2LConfProfTxRefVnUs[MAX_LEN_512];
	size_t xdsl2LConfProfTxRefVnUs_len;
	char old_xdsl2LConfProfTxRefVnUs[MAX_LEN_512];
	size_t old_xdsl2LConfProfTxRefVnUs_len;
	ulong xdsl2LConfProfXtuTransSysEna;
	ulong old_xdsl2LConfProfXtuTransSysEna;
	uint8_t xdsl2LConfProfPmMode;
	uint8_t old_xdsl2LConfProfPmMode;
	size_t old_xdsl2LConfProfPmMode_len;
	u_long xdsl2LConfProfL0Time;
	u_long old_xdsl2LConfProfL0Time;
	u_long xdsl2LConfProfL2Time;
	u_long old_xdsl2LConfProfL2Time;
	u_long xdsl2LConfProfL2Atpr;
	u_long old_xdsl2LConfProfL2Atpr;
	u_long xdsl2LConfProfL2Atprt;
	u_long old_xdsl2LConfProfL2Atprt;
	char xdsl2LConfProfProfiles[MAX_LEN_32];
	size_t xdsl2LConfProfProfiles_len;
	char old_xdsl2LConfProfProfiles[MAX_LEN_32];
	size_t old_xdsl2LConfProfProfiles_len;
	char xdsl2LConfProfDpboEPsd[MAX_LEN_512];
	size_t xdsl2LConfProfDpboEPsd_len;
	char old_xdsl2LConfProfDpboEPsd[MAX_LEN_512];
	size_t old_xdsl2LConfProfDpboEPsd_len;
	u_long xdsl2LConfProfDpboEsEL;
	u_long old_xdsl2LConfProfDpboEsEL;
	u_long xdsl2LConfProfDpboEsCableModelA;
	u_long old_xdsl2LConfProfDpboEsCableModelA;
	u_long xdsl2LConfProfDpboEsCableModelB;
	u_long old_xdsl2LConfProfDpboEsCableModelB;
	u_long xdsl2LConfProfDpboEsCableModelC;
	u_long old_xdsl2LConfProfDpboEsCableModelC;
	u_long xdsl2LConfProfDpboMus;
	u_long old_xdsl2LConfProfDpboMus;
	u_long xdsl2LConfProfDpboFMin;
	u_long old_xdsl2LConfProfDpboFMin;
	u_long xdsl2LConfProfDpboFMax;
	u_long old_xdsl2LConfProfDpboFMax;
	u_long xdsl2LConfProfUpboKL;
	u_long old_xdsl2LConfProfUpboKL;
	long xdsl2LConfProfUpboKLF;
	long old_xdsl2LConfProfUpboKLF;
	uint xdsl2LConfProfUs0Mask;
	uint old_xdsl2LConfProfUs0Mask;
	long xdsl2LConfProfForceInp;
	long old_xdsl2LConfProfForceInp;
	long xdsl2LConfProfRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineConfProfTable_entry* next;
};

struct xdsl2LineConfProfTable_entry* xdsl2LineConfProfTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineConfProfTable_entry*
	xdsl2LineConfProfTable_createEntry(unsigned char* xdsl2LConfProfProfileName, size_t xdsl2LConfProfProfileName_len) {
	struct xdsl2LineConfProfTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineConfProfTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LConfProfProfileName, xdsl2LConfProfProfileName, xdsl2LConfProfProfileName_len);
	entry->xdsl2LConfProfProfileName_len = xdsl2LConfProfProfileName_len;
	entry->next = xdsl2LineConfProfTable_head;
	xdsl2LineConfProfTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineConfProfTable_removeEntry(struct xdsl2LineConfProfTable_entry* entry) {
	struct xdsl2LineConfProfTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineConfProfTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineConfProfTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineConfProfTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineConfProfTable_head;
	return xdsl2LineConfProfTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineConfProfTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineConfProfTable_entry* entry = (struct xdsl2LineConfProfTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LConfProfProfileName, sizeof(entry->xdsl2LConfProfProfileName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineConfProfTable table */
int
xdsl2LineConfProfTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineConfProfTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineConfProfTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFSCMASKDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfScMaskDs,
					table_entry->xdsl2LConfProfScMaskDs_len);
				break;
			case COLUMN_XDSL2LCONFPROFSCMASKUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfScMaskUs,
					table_entry->xdsl2LConfProfScMaskUs_len);
				break;
			case COLUMN_XDSL2LCONFPROFVDSL2CARMASK:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfVdsl2CarMask,
					table_entry->xdsl2LConfProfVdsl2CarMask_len);
				break;
			case COLUMN_XDSL2LCONFPROFRFIBANDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfRfiBands,
					table_entry->xdsl2LConfProfRfiBands_len);
				break;
			case COLUMN_XDSL2LCONFPROFRAMODEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfRaModeDs);
				break;
			case COLUMN_XDSL2LCONFPROFRAMODEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfRaModeUs);
				break;
			case COLUMN_XDSL2LCONFPROFRAUSNRMDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaUsNrmDs);
				break;
			case COLUMN_XDSL2LCONFPROFRAUSNRMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaUsNrmUs);
				break;
			case COLUMN_XDSL2LCONFPROFRAUSTIMEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaUsTimeDs);
				break;
			case COLUMN_XDSL2LCONFPROFRAUSTIMEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaUsTimeUs);
				break;
			case COLUMN_XDSL2LCONFPROFRADSNRMDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaDsNrmDs);
				break;
			case COLUMN_XDSL2LCONFPROFRADSNRMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaDsNrmUs);
				break;
			case COLUMN_XDSL2LCONFPROFRADSTIMEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaDsTimeDs);
				break;
			case COLUMN_XDSL2LCONFPROFRADSTIMEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfRaDsTimeUs);
				break;
			case COLUMN_XDSL2LCONFPROFTARGETSNRMDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfTargetSnrmDs);
				break;
			case COLUMN_XDSL2LCONFPROFTARGETSNRMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfTargetSnrmUs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXSNRMDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMaxSnrmDs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXSNRMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMaxSnrmUs);
				break;
			case COLUMN_XDSL2LCONFPROFMINSNRMDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMinSnrmDs);
				break;
			case COLUMN_XDSL2LCONFPROFMINSNRMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMinSnrmUs);
				break;
			case COLUMN_XDSL2LCONFPROFMSGMINUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMsgMinUs);
				break;
			case COLUMN_XDSL2LCONFPROFMSGMINDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMsgMinDs);
				break;
			case COLUMN_XDSL2LCONFPROFCEFLAG:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfCeFlag,sizeof(table_entry->xdsl2LConfProfCeFlag));
				break;
			case COLUMN_XDSL2LCONFPROFSNRMODEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfSnrModeDs);
				break;
			case COLUMN_XDSL2LCONFPROFSNRMODEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfSnrModeUs);
				break;
			case COLUMN_XDSL2LCONFPROFTXREFVNDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfTxRefVnDs,
					table_entry->xdsl2LConfProfTxRefVnDs_len);
				break;
			case COLUMN_XDSL2LCONFPROFTXREFVNUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfTxRefVnUs,
					table_entry->xdsl2LConfProfTxRefVnUs_len);
				break;
			case COLUMN_XDSL2LCONFPROFXTUTRANSSYSENA:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfXtuTransSysEna, sizeof(table_entry->xdsl2LConfProfXtuTransSysEna));
				break;
			case COLUMN_XDSL2LCONFPROFPMMODE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfPmMode, sizeof(table_entry->xdsl2LConfProfPmMode));
				break;
			case COLUMN_XDSL2LCONFPROFL0TIME:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfL0Time);
				break;
			case COLUMN_XDSL2LCONFPROFL2TIME:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfL2Time);
				break;
			case COLUMN_XDSL2LCONFPROFL2ATPR:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfL2Atpr);
				break;
			case COLUMN_XDSL2LCONFPROFL2ATPRT:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfL2Atprt);
				break;
			case COLUMN_XDSL2LCONFPROFPROFILES:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfProfiles,
					table_entry->xdsl2LConfProfProfiles_len);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOEPSD:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfDpboEPsd,
					table_entry->xdsl2LConfProfDpboEPsd_len);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESEL:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboEsEL);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELA:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboEsCableModelA);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELB:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboEsCableModelB);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELC:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboEsCableModelC);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOMUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboMus);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOFMIN:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboFMin);
				break;
			case COLUMN_XDSL2LCONFPROFDPBOFMAX:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfDpboFMax);
				break;
			case COLUMN_XDSL2LCONFPROFUPBOKL:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfUpboKL);
				break;
			case COLUMN_XDSL2LCONFPROFUPBOKLF:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfUpboKLF);
				break;
			case COLUMN_XDSL2LCONFPROFUS0MASK:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfUs0Mask, sizeof(table_entry->xdsl2LConfProfUs0Mask));
				break;
			case COLUMN_XDSL2LCONFPROFFORCEINP:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfForceInp);
				break;
			case COLUMN_XDSL2LCONFPROFROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFSCMASKDS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfScMaskDs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFSCMASKUS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfScMaskUs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFVDSL2CARMASK:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfVdsl2CarMask));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRFIBANDS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfRfiBands));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAMODEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAMODEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAUSNRMDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAUSNRMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAUSTIMEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRAUSTIMEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRADSNRMDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRADSNRMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRADSTIMEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFRADSTIMEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFTARGETSNRMDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFTARGETSNRMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXSNRMDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXSNRMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMINSNRMDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMINSNRMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMSGMINUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMSGMINDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFCEFLAG:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfCeFlag));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFSNRMODEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFSNRMODEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFTXREFVNDS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfTxRefVnDs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFTXREFVNUS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfTxRefVnUs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFXTUTRANSSYSENA:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfXtuTransSysEna));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFPMMODE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfPmMode));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFL0TIME:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFL2TIME:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFL2ATPR:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFL2ATPRT:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFPROFILES:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfProfiles));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOEPSD:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfDpboEPsd));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESEL:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELA:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELB:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOESCABLEMODELC:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOMUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOFMIN:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFDPBOFMAX:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFUPBOKL:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFUPBOKLF:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFUS0MASK:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfUs0Mask));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFFORCEINP:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineConfProfTable_entry* table_row = xdsl2LineConfProfTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfProfTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2LConfProfRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2LConfProfRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2LineConfProfTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
