/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMLINEINITCURRTABLE_H
#define XDSL2PMLINEINITCURRTABLE_H

/* function declarations */
void init_xdsl2PMLineInitCurrTable(void);
void initialize_table_xdsl2PMLineInitCurrTable(void);
Netsnmp_Node_Handler xdsl2PMLineInitCurrTable_handler;
Netsnmp_First_Data_Point  xdsl2PMLineInitCurrTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMLineInitCurrTable_get_next_data_point;

/* column number definitions for table xdsl2PMLineInitCurrTable */
       #define COLUMN_XDSL2PMLINITCURR15MVALIDINTERVALS		1
       #define COLUMN_XDSL2PMLINITCURR15MINVALIDINTERVALS		2
       #define COLUMN_XDSL2PMLINITCURR15MTIMEELAPSED		3
       #define COLUMN_XDSL2PMLINITCURR15MFULLINITS		4
       #define COLUMN_XDSL2PMLINITCURR15MFAILEDFULLINITS		5
       #define COLUMN_XDSL2PMLINITCURR15MSHORTINITS		6
       #define COLUMN_XDSL2PMLINITCURR15MFAILEDSHORTINITS		7
       #define COLUMN_XDSL2PMLINITCURR1DAYVALIDINTERVALS		8
       #define COLUMN_XDSL2PMLINITCURR1DAYINVALIDINTERVALS		9
       #define COLUMN_XDSL2PMLINITCURR1DAYTIMEELAPSED		10
       #define COLUMN_XDSL2PMLINITCURR1DAYFULLINITS		11
       #define COLUMN_XDSL2PMLINITCURR1DAYFAILEDFULLINITS		12
       #define COLUMN_XDSL2PMLINITCURR1DAYSHORTINITS		13
       #define COLUMN_XDSL2PMLINITCURR1DAYFAILEDSHORTINITS		14
#endif /* XDSL2PMLINEINITCURRTABLE_H */
