/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2PMChCurrTable.h"

/** Initializes the xdsl2PMChCurrTable module */
void
init_xdsl2PMChCurrTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2PMChCurrTable();
}


/** Initialize the xdsl2PMChCurrTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2PMChCurrTable(void)
{
    const oid xdsl2PMChCurrTable_oid[] = {1,3,6,1,2,1,10,251,1,4,2,1};
    const size_t xdsl2PMChCurrTable_oid_len   = OID_LENGTH(xdsl2PMChCurrTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2PMChCurrTable:init", "initializing table xdsl2PMChCurrTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2PMChCurrTable",     xdsl2PMChCurrTable_handler,
              xdsl2PMChCurrTable_oid, xdsl2PMChCurrTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2PMChCurrUnit */
                           0);
    table_info->min_column = COLUMN_XDSL2PMCHCURR15MVALIDINTERVALS;
    table_info->max_column = COLUMN_XDSL2PMCHCURR1DAYCORRECTEDBLOCKS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2PMChCurrTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2PMChCurrTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2PMChCurrTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2PMChCurrUnit;

    /* Column values */
    u_long xdsl2PMChCurr15MValidIntervals;
    u_long xdsl2PMChCurr15MInvalidIntervals;
    long xdsl2PMChCurr15MTimeElapsed;
    u_long xdsl2PMChCurr15MCodingViolations;
    u_long xdsl2PMChCurr15MCorrectedBlocks;
    u_long xdsl2PMChCurr1DayValidIntervals;
    u_long xdsl2PMChCurr1DayInvalidIntervals;
    long xdsl2PMChCurr1DayTimeElapsed;
    u_long xdsl2PMChCurr1DayCodingViolations;
    u_long xdsl2PMChCurr1DayCorrectedBlocks;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2PMChCurrTable_entry *next;
};

struct xdsl2PMChCurrTable_entry  *xdsl2PMChCurrTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2PMChCurrTable_entry *
xdsl2PMChCurrTable_createEntry(long ifIndex, long xdsl2PMChCurrUnit) {
    struct xdsl2PMChCurrTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2PMChCurrTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2PMChCurrUnit = xdsl2PMChCurrUnit;
    entry->next = xdsl2PMChCurrTable_head;
    xdsl2PMChCurrTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2PMChCurrTable_removeEntry( struct xdsl2PMChCurrTable_entry *entry ) {
    struct xdsl2PMChCurrTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2PMChCurrTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2PMChCurrTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2PMChCurrTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2PMChCurrTable_head;
    return xdsl2PMChCurrTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2PMChCurrTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2PMChCurrTable_entry *entry = (struct xdsl2PMChCurrTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2PMChCurrUnit );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2PMChCurrTable table */
int
xdsl2PMChCurrTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2PMChCurrTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2PMChCurrTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2PMChCurrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2PMCHCURR15MVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr15MValidIntervals);
                break;
            case COLUMN_XDSL2PMCHCURR15MINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr15MInvalidIntervals);
                break;
            case COLUMN_XDSL2PMCHCURR15MTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMChCurr15MTimeElapsed);
                break;
            case COLUMN_XDSL2PMCHCURR15MCODINGVIOLATIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr15MCodingViolations);
                break;
            case COLUMN_XDSL2PMCHCURR15MCORRECTEDBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr15MCorrectedBlocks);
                break;
            case COLUMN_XDSL2PMCHCURR1DAYVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr1DayValidIntervals);
                break;
            case COLUMN_XDSL2PMCHCURR1DAYINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr1DayInvalidIntervals);
                break;
            case COLUMN_XDSL2PMCHCURR1DAYTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMChCurr1DayTimeElapsed);
                break;
            case COLUMN_XDSL2PMCHCURR1DAYCODINGVIOLATIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr1DayCodingViolations);
                break;
            case COLUMN_XDSL2PMCHCURR1DAYCORRECTEDBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChCurr1DayCorrectedBlocks);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
