/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMCHHIST1DTABLE_H
#define XDSL2PMCHHIST1DTABLE_H

/* function declarations */
void init_xdsl2PMChHist1DTable(void);
void initialize_table_xdsl2PMChHist1DTable(void);
Netsnmp_Node_Handler xdsl2PMChHist1DTable_handler;
Netsnmp_First_Data_Point  xdsl2PMChHist1DTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMChHist1DTable_get_next_data_point;

/* column number definitions for table xdsl2PMChHist1DTable */
       #define COLUMN_XDSL2PMCHHIST1DUNIT		1
       #define COLUMN_XDSL2PMCHHIST1DINTERVAL		2
       #define COLUMN_XDSL2PMCHHIST1DMONITOREDTIME		3
       #define COLUMN_XDSL2PMCHHIST1DCODINGVIOLATIONS		4
       #define COLUMN_XDSL2PMCHHIST1DCORRECTEDBLOCKS		5
       #define COLUMN_XDSL2PMCHHIST1DVALIDINTERVAL		6
#endif /* XDSL2PMCHHIST1DTABLE_H */
