/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMLINEHIST1DAYTABLE_H
#define XDSL2PMLINEHIST1DAYTABLE_H

/* function declarations */
void init_xdsl2PMLineHist1DayTable(void);
void initialize_table_xdsl2PMLineHist1DayTable(void);
Netsnmp_Node_Handler xdsl2PMLineHist1DayTable_handler;
Netsnmp_First_Data_Point  xdsl2PMLineHist1DayTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMLineHist1DayTable_get_next_data_point;

/* column number definitions for table xdsl2PMLineHist1DayTable */
       #define COLUMN_XDSL2PMLHIST1DUNIT		1
       #define COLUMN_XDSL2PMLHIST1DINTERVAL		2
       #define COLUMN_XDSL2PMLHIST1DMONITOREDTIME		3
       #define COLUMN_XDSL2PMLHIST1DFECS		4
       #define COLUMN_XDSL2PMLHIST1DES		5
       #define COLUMN_XDSL2PMLHIST1DSES		6
       #define COLUMN_XDSL2PMLHIST1DLOSS		7
       #define COLUMN_XDSL2PMLHIST1DUAS		8
       #define COLUMN_XDSL2PMLHIST1DVALIDINTERVAL		9
#endif /* XDSL2PMLINEHIST1DAYTABLE_H */
