/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2SCSTATUSBANDTABLE_H
#define XDSL2SCSTATUSBANDTABLE_H

/* function declarations */
void init_xdsl2SCStatusBandTable(void);
void initialize_table_xdsl2SCStatusBandTable(void);
Netsnmp_Node_Handler xdsl2SCStatusBandTable_handler;
Netsnmp_First_Data_Point  xdsl2SCStatusBandTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2SCStatusBandTable_get_next_data_point;

/* column number definitions for table xdsl2SCStatusBandTable */
       #define COLUMN_XDSL2SCSTATUSBAND		1
       #define COLUMN_XDSL2SCSTATUSBANDLNATTEN		2
       #define COLUMN_XDSL2SCSTATUSBANDSIGATTEN		3
#endif /* XDSL2SCSTATUSBANDTABLE_H */
