/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2SCStatusTable.h"
#include "xdslctl_output_parser.h"

 /** Initializes the xdsl2SCStatusTable module */
void
init_xdsl2SCStatusTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2SCStatusTable();
}


/** Initialize the xdsl2SCStatusTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2SCStatusTable(void)
{
	const oid xdsl2SCStatusTable_oid[] = { 1,3,6,1,2,1,10,251,1,2,3 };
	const size_t xdsl2SCStatusTable_oid_len = OID_LENGTH(xdsl2SCStatusTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2SCStatusTable:init", "initializing table xdsl2SCStatusTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2SCStatusTable", xdsl2SCStatusTable_handler,
		xdsl2SCStatusTable_oid, xdsl2SCStatusTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_INTEGER,  /* index: ifIndex */
		ASN_INTEGER,  /* index: xdsl2SCStatusDirection */
		0);
	table_info->min_column = COLUMN_XDSL2SCSTATUSLINSCALE;
	table_info->max_column = COLUMN_XDSL2SCSTATUSROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2SCStatusTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2SCStatusTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2SCStatusTable_entry {
	/* Index values */
	long ifIndex;
	uint8_t xdsl2SCStatusDirection;

	/* Column values */
	uint16_t xdsl2SCStatusLinScale;
	uint8_t xdsl2SCStatusLinScGroupSize;
	uint16_t xdsl2SCStatusLogMt;
	uint8_t xdsl2SCStatusLogScGroupSize;
	uint16_t xdsl2SCStatusQlnMt;
	uint8_t xdsl2SCStatusQlnScGroupSize;
	uint16_t xdsl2SCStatusSnrMtime;
	uint8_t xdsl2SCStatusSnrScGroupSize;
	uint32_t xdsl2SCStatusAttainableRate;
	long xdsl2SCStatusRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2SCStatusTable_entry* next;
};

struct xdsl2SCStatusTable_entry* xdsl2SCStatusTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2SCStatusTable_entry*
	xdsl2SCStatusTable_createEntry(long ifIndex, long xdsl2SCStatusDirection) {
	struct xdsl2SCStatusTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2SCStatusTable_entry);
	if (!entry)
		return NULL;

	entry->ifIndex = ifIndex;
	entry->xdsl2SCStatusDirection = xdsl2SCStatusDirection;
	entry->next = xdsl2SCStatusTable_head;
	xdsl2SCStatusTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2SCStatusTable_removeEntry(struct xdsl2SCStatusTable_entry* entry) {
	struct xdsl2SCStatusTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2SCStatusTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2SCStatusTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2SCStatusTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2SCStatusTable_head;
	return xdsl2SCStatusTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2SCStatusTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2SCStatusTable_entry* entry = (struct xdsl2SCStatusTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->ifIndex);
		idx = idx->next_variable;
		snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->xdsl2SCStatusDirection);
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2SCStatusTable table */
int
xdsl2SCStatusTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2SCStatusTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2SCStatusTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2SCStatusTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2SCSTATUSLINSCALE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusLinScale);
				break;
			case COLUMN_XDSL2SCSTATUSLINSCGROUPSIZE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusLinScGroupSize);
				break;
			case COLUMN_XDSL2SCSTATUSLOGMT:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusLogMt);
				break;
			case COLUMN_XDSL2SCSTATUSLOGSCGROUPSIZE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusLogScGroupSize);
				break;
			case COLUMN_XDSL2SCSTATUSQLNMT:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusQlnMt);
				break;
			case COLUMN_XDSL2SCSTATUSQLNSCGROUPSIZE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusQlnScGroupSize);
				break;
			case COLUMN_XDSL2SCSTATUSSNRMTIME:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusSnrMtime);
				break;
			case COLUMN_XDSL2SCSTATUSSNRSCGROUPSIZE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusSnrScGroupSize);
				break;
			case COLUMN_XDSL2SCSTATUSATTAINABLERATE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2SCStatusAttainableRate);
				break;
			case COLUMN_XDSL2SCSTATUSROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2SCStatusRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2SCStatusTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2SCSTATUSROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		break;

	case MODE_SET_FREE:
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2SCStatusTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2SCStatusTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2SCSTATUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2SCStatusTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2SCSTATUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2SCStatusTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		break;
	}
	return SNMP_ERR_NOERROR;
}
