/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2Notifications.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_xdsl2LinePerfFECSThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfFECSThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,1 };
    const oid xdsl2PMLCurr15MFecs_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,5, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXtucThresh15MinFecs_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,2, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfFECSThreshXtuc_oid, sizeof(xdsl2LinePerfFECSThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MFecs_oid, OID_LENGTH(xdsl2PMLCurr15MFecs_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MFecs */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXtucThresh15MinFecs_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXtucThresh15MinFecs_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXtucThresh15MinFecs */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfFECSThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfFECSThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,2 };
    const oid xdsl2PMLCurr15MFecs_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,5, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXturThresh15MinFecs_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,7, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfFECSThreshXtur_oid, sizeof(xdsl2LinePerfFECSThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MFecs_oid, OID_LENGTH(xdsl2PMLCurr15MFecs_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MFecs */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXturThresh15MinFecs_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXturThresh15MinFecs_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXturThresh15MinFecs */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfESThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfESThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,3 };
    const oid xdsl2PMLCurr15MEs_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,6, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXtucThresh15MinEs_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfESThreshXtuc_oid, sizeof(xdsl2LinePerfESThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MEs_oid, OID_LENGTH(xdsl2PMLCurr15MEs_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MEs */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXtucThresh15MinEs_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXtucThresh15MinEs_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXtucThresh15MinEs */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfESThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfESThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,4 };
    const oid xdsl2PMLCurr15MEs_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,6, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXturThresh15MinEs_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,8, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfESThreshXtur_oid, sizeof(xdsl2LinePerfESThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MEs_oid, OID_LENGTH(xdsl2PMLCurr15MEs_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MEs */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXturThresh15MinEs_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXturThresh15MinEs_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXturThresh15MinEs */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfSESThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfSESThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,5 };
    const oid xdsl2PMLCurr15MSes_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,7, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXtucThresh15MinSes_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,4, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfSESThreshXtuc_oid, sizeof(xdsl2LinePerfSESThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MSes_oid, OID_LENGTH(xdsl2PMLCurr15MSes_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MSes */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXtucThresh15MinSes_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXtucThresh15MinSes_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXtucThresh15MinSes */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfSESThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfSESThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,6 };
    const oid xdsl2PMLCurr15MSes_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,7, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXturThresh15MinSes_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,9, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfSESThreshXtur_oid, sizeof(xdsl2LinePerfSESThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MSes_oid, OID_LENGTH(xdsl2PMLCurr15MSes_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MSes */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXturThresh15MinSes_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXturThresh15MinSes_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXturThresh15MinSes */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfLOSSThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfLOSSThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,7 };
    const oid xdsl2PMLCurr15MLoss_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,8, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXtucThresh15MinLoss_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,5, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfLOSSThreshXtuc_oid, sizeof(xdsl2LinePerfLOSSThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MLoss_oid, OID_LENGTH(xdsl2PMLCurr15MLoss_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MLoss */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXtucThresh15MinLoss_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXtucThresh15MinLoss_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXtucThresh15MinLoss */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfLOSSThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfLOSSThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,8 };
    const oid xdsl2PMLCurr15MLoss_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,8, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXturThresh15MinLoss_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,10, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfLOSSThreshXtur_oid, sizeof(xdsl2LinePerfLOSSThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MLoss_oid, OID_LENGTH(xdsl2PMLCurr15MLoss_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MLoss */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXturThresh15MinLoss_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXturThresh15MinLoss_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXturThresh15MinLoss */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfUASThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfUASThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,9 };
    const oid xdsl2PMLCurr15MUas_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,9, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXtucThresh15MinUas_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,6, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfUASThreshXtuc_oid, sizeof(xdsl2LinePerfUASThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MUas_oid, OID_LENGTH(xdsl2PMLCurr15MUas_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MUas */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXtucThresh15MinUas_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXtucThresh15MinUas_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXtucThresh15MinUas */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfUASThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfUASThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,10 };
    const oid xdsl2PMLCurr15MUas_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,1,1,9, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileXturThresh15MinUas_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,11, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfUASThreshXtur_oid, sizeof(xdsl2LinePerfUASThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLCurr15MUas_oid, OID_LENGTH(xdsl2PMLCurr15MUas_oid),
        ASN_COUNTER,
        /* Set an appropriate value for xdsl2PMLCurr15MUas */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileXturThresh15MinUas_oid, OID_LENGTH(xdsl2LineAlarmConfProfileXturThresh15MinUas_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileXturThresh15MinUas */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfCodingViolationsThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfCodingViolationsThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,11 };
    const oid xdsl2PMChCurr15MCodingViolations_oid[] = { 1,3,6,1,2,1,10,251,1,4,2,1,1,5, /* insert index here */ };
    const oid xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,3,1,2, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfCodingViolationsThreshXtuc_oid, sizeof(xdsl2LinePerfCodingViolationsThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMChCurr15MCodingViolations_oid, OID_LENGTH(xdsl2PMChCurr15MCodingViolations_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMChCurr15MCodingViolations */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations_oid, OID_LENGTH(xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfCodingViolationsThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfCodingViolationsThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,12 };
    const oid xdsl2PMChCurr15MCodingViolations_oid[] = { 1,3,6,1,2,1,10,251,1,4,2,1,1,5, /* insert index here */ };
    const oid xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,3,1,4, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfCodingViolationsThreshXtur_oid, sizeof(xdsl2LinePerfCodingViolationsThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMChCurr15MCodingViolations_oid, OID_LENGTH(xdsl2PMChCurr15MCodingViolations_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMChCurr15MCodingViolations */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations_oid, OID_LENGTH(xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfCorrectedThreshXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfCorrectedThreshXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,13 };
    const oid xdsl2PMChCurr15MCorrectedBlocks_oid[] = { 1,3,6,1,2,1,10,251,1,4,2,1,1,6, /* insert index here */ };
    const oid xdsl2ChAlarmConfProfileXtucThresh15MinCorrected_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,3,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfCorrectedThreshXtuc_oid, sizeof(xdsl2LinePerfCorrectedThreshXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMChCurr15MCorrectedBlocks_oid, OID_LENGTH(xdsl2PMChCurr15MCorrectedBlocks_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMChCurr15MCorrectedBlocks */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2ChAlarmConfProfileXtucThresh15MinCorrected_oid, OID_LENGTH(xdsl2ChAlarmConfProfileXtucThresh15MinCorrected_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2ChAlarmConfProfileXtucThresh15MinCorrected */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfCorrectedThreshXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfCorrectedThreshXtur_oid[] = { 1,3,6,1,2,1,10,251,0,14 };
    const oid xdsl2PMChCurr15MCorrectedBlocks_oid[] = { 1,3,6,1,2,1,10,251,1,4,2,1,1,6, /* insert index here */ };
    const oid xdsl2ChAlarmConfProfileXturThresh15MinCorrected_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,3,1,5, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfCorrectedThreshXtur_oid, sizeof(xdsl2LinePerfCorrectedThreshXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMChCurr15MCorrectedBlocks_oid, OID_LENGTH(xdsl2PMChCurr15MCorrectedBlocks_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMChCurr15MCorrectedBlocks */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2ChAlarmConfProfileXturThresh15MinCorrected_oid, OID_LENGTH(xdsl2ChAlarmConfProfileXturThresh15MinCorrected_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2ChAlarmConfProfileXturThresh15MinCorrected */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfFailedFullInitThresh_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfFailedFullInitThresh_oid[] = { 1,3,6,1,2,1,10,251,0,15 };
    const oid xdsl2PMLInitCurr15MFailedFullInits_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,2,1,5, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileThresh15MinFailedFullInt_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,12, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfFailedFullInitThresh_oid, sizeof(xdsl2LinePerfFailedFullInitThresh_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLInitCurr15MFailedFullInits_oid, OID_LENGTH(xdsl2PMLInitCurr15MFailedFullInits_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMLInitCurr15MFailedFullInits */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileThresh15MinFailedFullInt_oid, OID_LENGTH(xdsl2LineAlarmConfProfileThresh15MinFailedFullInt_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileThresh15MinFailedFullInt */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LinePerfFailedShortInitThresh_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LinePerfFailedShortInitThresh_oid[] = { 1,3,6,1,2,1,10,251,0,16 };
    const oid xdsl2PMLInitCurr15MFailedShortInits_oid[] = { 1,3,6,1,2,1,10,251,1,4,1,2,1,7, /* insert index here */ };
    const oid xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2,1,13, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LinePerfFailedShortInitThresh_oid, sizeof(xdsl2LinePerfFailedShortInitThresh_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2PMLInitCurr15MFailedShortInits_oid, OID_LENGTH(xdsl2PMLInitCurr15MFailedShortInits_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2PMLInitCurr15MFailedShortInits */
        NULL, 0);
    snmp_varlist_add_variable(&var_list,
        xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt_oid, OID_LENGTH(xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt_oid),
        ASN_UNSIGNED,
        /* Set an appropriate value for xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LineStatusChangeXtuc_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LineStatusChangeXtuc_oid[] = { 1,3,6,1,2,1,10,251,0,17 };
    const oid xdsl2LineStatusXtuc_oid[] = { 1,3,6,1,2,1,10,251,1,1,1,1,19, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LineStatusChangeXtuc_oid, sizeof(xdsl2LineStatusChangeXtuc_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2LineStatusXtuc_oid, OID_LENGTH(xdsl2LineStatusXtuc_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for xdsl2LineStatusXtuc */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xdsl2LineStatusChangeXtur_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xdsl2LineStatusChangeXtur_oid[] = { 1,3,6,1,2,1,10,251,0,18 };
    const oid xdsl2LineStatusXtur_oid[] = { 1,3,6,1,2,1,10,251,1,1,1,1,18, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xdsl2LineStatusChangeXtur_oid, sizeof(xdsl2LineStatusChangeXtur_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xdsl2LineStatusXtur_oid, OID_LENGTH(xdsl2LineStatusXtur_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for xdsl2LineStatusXtur */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
