/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineConfTemplateTable.h"

 /** Initializes the xdsl2LineConfTemplateTable module */
void
init_xdsl2LineConfTemplateTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineConfTemplateTable();
}


/** Initialize the xdsl2LineConfTemplateTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineConfTemplateTable(void)
{
	const oid xdsl2LineConfTemplateTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,1,1 };
	const size_t xdsl2LineConfTemplateTable_oid_len = OID_LENGTH(xdsl2LineConfTemplateTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineConfTemplateTable:init", "initializing table xdsl2LineConfTemplateTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineConfTemplateTable", xdsl2LineConfTemplateTable_handler,
		xdsl2LineConfTemplateTable_oid, xdsl2LineConfTemplateTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LConfTempTemplateName */
		0);
	table_info->min_column = COLUMN_XDSL2LCONFTEMPLINEPROFILE;
	table_info->max_column = COLUMN_XDSL2LCONFTEMPROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineConfTemplateTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineConfTemplateTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineConfTemplateTable_entry {
	/* Index values */
	char xdsl2LConfTempTemplateName[MAX_LEN_32];
	size_t xdsl2LConfTempTemplateName_len;

	/* Column values */
	char xdsl2LConfTempLineProfile[MAX_LEN_32];
	size_t xdsl2LConfTempLineProfile_len;
	char old_xdsl2LConfTempLineProfile[MAX_LEN_32];
	size_t old_xdsl2LConfTempLineProfile_len;
	char xdsl2LConfTempChan1ConfProfile[MAX_LEN_32];
	size_t xdsl2LConfTempChan1ConfProfile_len;
	char old_xdsl2LConfTempChan1ConfProfile[MAX_LEN_32];
	size_t old_xdsl2LConfTempChan1ConfProfile_len;
	u_long xdsl2LConfTempChan1RaRatioDs;
	u_long old_xdsl2LConfTempChan1RaRatioDs;
	u_long xdsl2LConfTempChan1RaRatioUs;
	u_long old_xdsl2LConfTempChan1RaRatioUs;
	char xdsl2LConfTempChan2ConfProfile[MAX_LEN_32];
	size_t xdsl2LConfTempChan2ConfProfile_len;
	char old_xdsl2LConfTempChan2ConfProfile[MAX_LEN_32];
	size_t old_xdsl2LConfTempChan2ConfProfile_len;
	u_long xdsl2LConfTempChan2RaRatioDs;
	u_long old_xdsl2LConfTempChan2RaRatioDs;
	u_long xdsl2LConfTempChan2RaRatioUs;
	u_long old_xdsl2LConfTempChan2RaRatioUs;
	char xdsl2LConfTempChan3ConfProfile[MAX_LEN_32];
	size_t xdsl2LConfTempChan3ConfProfile_len;
	char old_xdsl2LConfTempChan3ConfProfile[MAX_LEN_32];
	size_t old_xdsl2LConfTempChan3ConfProfile_len;
	u_long xdsl2LConfTempChan3RaRatioDs;
	u_long old_xdsl2LConfTempChan3RaRatioDs;
	u_long xdsl2LConfTempChan3RaRatioUs;
	u_long old_xdsl2LConfTempChan3RaRatioUs;
	char xdsl2LConfTempChan4ConfProfile[MAX_LEN_32];
	size_t xdsl2LConfTempChan4ConfProfile_len;
	char old_xdsl2LConfTempChan4ConfProfile[MAX_LEN_32];
	size_t old_xdsl2LConfTempChan4ConfProfile_len;
	u_long xdsl2LConfTempChan4RaRatioDs;
	u_long old_xdsl2LConfTempChan4RaRatioDs;
	u_long xdsl2LConfTempChan4RaRatioUs;
	u_long old_xdsl2LConfTempChan4RaRatioUs;
	long xdsl2LConfTempRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineConfTemplateTable_entry* next;
};

struct xdsl2LineConfTemplateTable_entry* xdsl2LineConfTemplateTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineConfTemplateTable_entry*
	xdsl2LineConfTemplateTable_createEntry(unsigned char* xdsl2LConfTempTemplateName, size_t xdsl2LConfTempTemplateName_len) {
	struct xdsl2LineConfTemplateTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineConfTemplateTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LConfTempTemplateName, xdsl2LConfTempTemplateName, xdsl2LConfTempTemplateName_len);
	entry->xdsl2LConfTempTemplateName_len = xdsl2LConfTempTemplateName_len;
	entry->next = xdsl2LineConfTemplateTable_head;
	xdsl2LineConfTemplateTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineConfTemplateTable_removeEntry(struct xdsl2LineConfTemplateTable_entry* entry) {
	struct xdsl2LineConfTemplateTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineConfTemplateTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineConfTemplateTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineConfTemplateTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineConfTemplateTable_head;
	return xdsl2LineConfTemplateTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineConfTemplateTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineConfTemplateTable_entry* entry = (struct xdsl2LineConfTemplateTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LConfTempTemplateName, sizeof(entry->xdsl2LConfTempTemplateName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineConfTemplateTable table */
int
xdsl2LineConfTemplateTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineConfTemplateTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineConfTemplateTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPLINEPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfTempLineProfile,
					table_entry->xdsl2LConfTempLineProfile_len);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfTempChan1ConfProfile,
					table_entry->xdsl2LConfTempChan1ConfProfile_len);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIODS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan1RaRatioDs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIOUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan1RaRatioUs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfTempChan2ConfProfile,
					table_entry->xdsl2LConfTempChan2ConfProfile_len);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIODS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan2RaRatioDs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIOUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan2RaRatioUs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfTempChan3ConfProfile,
					table_entry->xdsl2LConfTempChan3ConfProfile_len);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIODS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan3RaRatioDs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIOUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan3RaRatioUs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfTempChan4ConfProfile,
					table_entry->xdsl2LConfTempChan4ConfProfile_len);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIODS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan4RaRatioDs);
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIOUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfTempChan4RaRatioUs);
				break;
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfTempRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPLINEPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfTempLineProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfTempChan1ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIODS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIOUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfTempChan2ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIODS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIOUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfTempChan3ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIODS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIOUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfTempChan4ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIODS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIOUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineConfTemplateTable_entry* table_row = xdsl2LineConfTemplateTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfTemplateTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPLINEPROFILE:
				memcpy(table_entry->old_xdsl2LConfTempLineProfile,
					table_entry->xdsl2LConfTempLineProfile,
					sizeof(table_entry->xdsl2LConfTempLineProfile));
				table_entry->old_xdsl2LConfTempLineProfile_len =
					table_entry->xdsl2LConfTempLineProfile_len;
				memset(table_entry->xdsl2LConfTempLineProfile, 0,
					sizeof(table_entry->xdsl2LConfTempLineProfile));
				memcpy(table_entry->xdsl2LConfTempLineProfile,
					request->requestvb->val.string,
					request->requestvb->val_len);
				table_entry->xdsl2LConfTempLineProfile_len =
					request->requestvb->val_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1CONFPROFILE:
				memcpy(table_entry->old_xdsl2LConfTempChan1ConfProfile,
					table_entry->xdsl2LConfTempChan1ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan1ConfProfile));
				table_entry->old_xdsl2LConfTempChan1ConfProfile_len =
					table_entry->xdsl2LConfTempChan1ConfProfile_len;
				memset(table_entry->xdsl2LConfTempChan1ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan1ConfProfile));
				memcpy(table_entry->xdsl2LConfTempChan1ConfProfile,
					request->requestvb->val.string,
					request->requestvb->val_len);
				table_entry->xdsl2LConfTempChan1ConfProfile_len =
					request->requestvb->val_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIODS:
				table_entry->old_xdsl2LConfTempChan1RaRatioDs = table_entry->xdsl2LConfTempChan1RaRatioDs;
				table_entry->xdsl2LConfTempChan1RaRatioDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIOUS:
				table_entry->old_xdsl2LConfTempChan1RaRatioUs = table_entry->xdsl2LConfTempChan1RaRatioUs;
				table_entry->xdsl2LConfTempChan1RaRatioUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2CONFPROFILE:
				memcpy(table_entry->old_xdsl2LConfTempChan2ConfProfile,
					table_entry->xdsl2LConfTempChan2ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan2ConfProfile));
				table_entry->old_xdsl2LConfTempChan2ConfProfile_len =
					table_entry->xdsl2LConfTempChan2ConfProfile_len;
				memset(table_entry->xdsl2LConfTempChan2ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan2ConfProfile));
				memcpy(table_entry->xdsl2LConfTempChan2ConfProfile,
					request->requestvb->val.string,
					request->requestvb->val_len);
				table_entry->xdsl2LConfTempChan2ConfProfile_len =
					request->requestvb->val_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIODS:
				table_entry->old_xdsl2LConfTempChan2RaRatioDs = table_entry->xdsl2LConfTempChan2RaRatioDs;
				table_entry->xdsl2LConfTempChan2RaRatioDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIOUS:
				table_entry->old_xdsl2LConfTempChan2RaRatioUs = table_entry->xdsl2LConfTempChan2RaRatioUs;
				table_entry->xdsl2LConfTempChan2RaRatioUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3CONFPROFILE:
				memcpy(table_entry->old_xdsl2LConfTempChan3ConfProfile,
					table_entry->xdsl2LConfTempChan3ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan3ConfProfile));
				table_entry->old_xdsl2LConfTempChan3ConfProfile_len =
					table_entry->xdsl2LConfTempChan3ConfProfile_len;
				memset(table_entry->xdsl2LConfTempChan3ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan3ConfProfile));
				memcpy(table_entry->xdsl2LConfTempChan3ConfProfile,
					request->requestvb->val.string,
					request->requestvb->val_len);
				table_entry->xdsl2LConfTempChan3ConfProfile_len =
					request->requestvb->val_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIODS:
				table_entry->old_xdsl2LConfTempChan3RaRatioDs = table_entry->xdsl2LConfTempChan3RaRatioDs;
				table_entry->xdsl2LConfTempChan3RaRatioDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIOUS:
				table_entry->old_xdsl2LConfTempChan3RaRatioUs = table_entry->xdsl2LConfTempChan3RaRatioUs;
				table_entry->xdsl2LConfTempChan3RaRatioUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4CONFPROFILE:
				memcpy(table_entry->old_xdsl2LConfTempChan4ConfProfile,
					table_entry->xdsl2LConfTempChan4ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan4ConfProfile));
				table_entry->old_xdsl2LConfTempChan4ConfProfile_len =
					table_entry->xdsl2LConfTempChan4ConfProfile_len;
				memset(table_entry->xdsl2LConfTempChan4ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan4ConfProfile));
				memcpy(table_entry->xdsl2LConfTempChan4ConfProfile,
					request->requestvb->val.string,
					request->requestvb->val_len);
				table_entry->xdsl2LConfTempChan4ConfProfile_len =
					request->requestvb->val_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIODS:
				table_entry->old_xdsl2LConfTempChan4RaRatioDs = table_entry->xdsl2LConfTempChan4RaRatioDs;
				table_entry->xdsl2LConfTempChan4RaRatioDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIOUS:
				table_entry->old_xdsl2LConfTempChan4RaRatioUs = table_entry->xdsl2LConfTempChan4RaRatioUs;
				table_entry->xdsl2LConfTempChan4RaRatioUs = *request->requestvb->val.integer;
				break;
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPLINEPROFILE:
				memcpy(table_entry->xdsl2LConfTempLineProfile,
					table_entry->old_xdsl2LConfTempLineProfile,
					sizeof(table_entry->xdsl2LConfTempLineProfile));
				memset(table_entry->old_xdsl2LConfTempLineProfile, 0,
					sizeof(table_entry->xdsl2LConfTempLineProfile));
				table_entry->xdsl2LConfTempLineProfile_len =
					table_entry->old_xdsl2LConfTempLineProfile_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1CONFPROFILE:
				memcpy(table_entry->xdsl2LConfTempChan1ConfProfile,
					table_entry->old_xdsl2LConfTempChan1ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan1ConfProfile));
				memset(table_entry->old_xdsl2LConfTempChan1ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan1ConfProfile));
				table_entry->xdsl2LConfTempChan1ConfProfile_len =
					table_entry->old_xdsl2LConfTempChan1ConfProfile_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIODS:
				table_entry->xdsl2LConfTempChan1RaRatioDs = table_entry->old_xdsl2LConfTempChan1RaRatioDs;
				table_entry->old_xdsl2LConfTempChan1RaRatioDs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN1RARATIOUS:
				table_entry->xdsl2LConfTempChan1RaRatioUs = table_entry->old_xdsl2LConfTempChan1RaRatioUs;
				table_entry->old_xdsl2LConfTempChan1RaRatioUs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2CONFPROFILE:
				memcpy(table_entry->xdsl2LConfTempChan2ConfProfile,
					table_entry->old_xdsl2LConfTempChan2ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan2ConfProfile));
				memset(table_entry->old_xdsl2LConfTempChan2ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan2ConfProfile));
				table_entry->xdsl2LConfTempChan2ConfProfile_len =
					table_entry->old_xdsl2LConfTempChan2ConfProfile_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIODS:
				table_entry->xdsl2LConfTempChan2RaRatioDs = table_entry->old_xdsl2LConfTempChan2RaRatioDs;
				table_entry->old_xdsl2LConfTempChan2RaRatioDs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN2RARATIOUS:
				table_entry->xdsl2LConfTempChan2RaRatioUs = table_entry->old_xdsl2LConfTempChan2RaRatioUs;
				table_entry->old_xdsl2LConfTempChan2RaRatioUs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3CONFPROFILE:
				memcpy(table_entry->xdsl2LConfTempChan3ConfProfile,
					table_entry->old_xdsl2LConfTempChan3ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan3ConfProfile));
				memset(table_entry->old_xdsl2LConfTempChan3ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan3ConfProfile));
				table_entry->xdsl2LConfTempChan3ConfProfile_len =
					table_entry->old_xdsl2LConfTempChan3ConfProfile_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIODS:
				table_entry->xdsl2LConfTempChan3RaRatioDs = table_entry->old_xdsl2LConfTempChan3RaRatioDs;
				table_entry->old_xdsl2LConfTempChan3RaRatioDs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN3RARATIOUS:
				table_entry->xdsl2LConfTempChan3RaRatioUs = table_entry->old_xdsl2LConfTempChan3RaRatioUs;
				table_entry->old_xdsl2LConfTempChan3RaRatioUs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4CONFPROFILE:
				memcpy(table_entry->xdsl2LConfTempChan4ConfProfile,
					table_entry->old_xdsl2LConfTempChan4ConfProfile,
					sizeof(table_entry->xdsl2LConfTempChan4ConfProfile));
				memset(table_entry->old_xdsl2LConfTempChan4ConfProfile, 0,
					sizeof(table_entry->xdsl2LConfTempChan4ConfProfile));
				table_entry->xdsl2LConfTempChan4ConfProfile_len =
					table_entry->old_xdsl2LConfTempChan4ConfProfile_len;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIODS:
				table_entry->xdsl2LConfTempChan4RaRatioDs = table_entry->old_xdsl2LConfTempChan4RaRatioDs;
				table_entry->old_xdsl2LConfTempChan4RaRatioDs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPCHAN4RARATIOUS:
				table_entry->xdsl2LConfTempChan4RaRatioUs = table_entry->old_xdsl2LConfTempChan4RaRatioUs;
				table_entry->old_xdsl2LConfTempChan4RaRatioUs = 0;
				break;
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfTemplateTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2LConfTempRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2LConfTempRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2LineConfTemplateTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
