/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2ChAlarmConfProfileTable.h"

 /** Initializes the xdsl2ChAlarmConfProfileTable module */
void
init_xdsl2ChAlarmConfProfileTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2ChAlarmConfProfileTable();
}


/** Initialize the xdsl2ChAlarmConfProfileTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2ChAlarmConfProfileTable(void)
{
	const oid xdsl2ChAlarmConfProfileTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,3 };
	const size_t xdsl2ChAlarmConfProfileTable_oid_len = OID_LENGTH(xdsl2ChAlarmConfProfileTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2ChAlarmConfProfileTable:init", "initializing table xdsl2ChAlarmConfProfileTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2ChAlarmConfProfileTable", xdsl2ChAlarmConfProfileTable_handler,
		xdsl2ChAlarmConfProfileTable_oid, xdsl2ChAlarmConfProfileTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2ChAlarmConfProfileName */
		0);
	table_info->min_column = COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS;
	table_info->max_column = COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2ChAlarmConfProfileTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2ChAlarmConfProfileTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2ChAlarmConfProfileTable_entry {
	/* Index values */
	char xdsl2ChAlarmConfProfileName[MAX_PROFILE_NAME_LEN];
	size_t xdsl2ChAlarmConfProfileName_len;

	/* Column values */
	u_long xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations;
	u_long old_xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations;
	u_long xdsl2ChAlarmConfProfileXtucThresh15MinCorrected;
	u_long old_xdsl2ChAlarmConfProfileXtucThresh15MinCorrected;
	u_long xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations;
	u_long old_xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations;
	u_long xdsl2ChAlarmConfProfileXturThresh15MinCorrected;
	u_long old_xdsl2ChAlarmConfProfileXturThresh15MinCorrected;
	long xdsl2ChAlarmConfProfileRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2ChAlarmConfProfileTable_entry* next;
};

struct xdsl2ChAlarmConfProfileTable_entry* xdsl2ChAlarmConfProfileTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2ChAlarmConfProfileTable_entry*
	xdsl2ChAlarmConfProfileTable_createEntry(
		unsigned char* xdsl2ChAlarmConfProfileName,
		size_t xdsl2ChAlarmConfProfileName_len) {
	struct xdsl2ChAlarmConfProfileTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2ChAlarmConfProfileTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2ChAlarmConfProfileName, xdsl2ChAlarmConfProfileName, xdsl2ChAlarmConfProfileName_len);
	entry->xdsl2ChAlarmConfProfileName_len = xdsl2ChAlarmConfProfileName_len;
	entry->next = xdsl2ChAlarmConfProfileTable_head;
	xdsl2ChAlarmConfProfileTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2ChAlarmConfProfileTable_removeEntry(struct xdsl2ChAlarmConfProfileTable_entry* entry) {
	struct xdsl2ChAlarmConfProfileTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2ChAlarmConfProfileTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2ChAlarmConfProfileTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2ChAlarmConfProfileTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2ChAlarmConfProfileTable_head;
	return xdsl2ChAlarmConfProfileTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2ChAlarmConfProfileTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2ChAlarmConfProfileTable_entry* entry = (struct xdsl2ChAlarmConfProfileTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2ChAlarmConfProfileName, sizeof(entry->xdsl2ChAlarmConfProfileName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2ChAlarmConfProfileTable table */
int
xdsl2ChAlarmConfProfileTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2ChAlarmConfProfileTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2ChAlarmConfProfileTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations);
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCORRECTED:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCorrected);
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCODINGVIOLATIONS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations);
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCORRECTED:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCorrected);
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChAlarmConfProfileRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCORRECTED:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCODINGVIOLATIONS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCORRECTED:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2ChAlarmConfProfileTable_entry* table_row = xdsl2ChAlarmConfProfileTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2ChAlarmConfProfileTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS:
				table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations = table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations;
				table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCORRECTED:
				table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCorrected = table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCorrected;
				table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCorrected = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCODINGVIOLATIONS:
				table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations = table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations;
				table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCORRECTED:
				table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCorrected = table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCorrected;
				table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCorrected = *request->requestvb->val.integer;
				break;
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS:
				table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations = table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations;
				table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCodingViolations = 0;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCORRECTED:
				table_entry->xdsl2ChAlarmConfProfileXtucThresh15MinCorrected = table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCorrected;
				table_entry->old_xdsl2ChAlarmConfProfileXtucThresh15MinCorrected = 0;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCODINGVIOLATIONS:
				table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations = table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations;
				table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCodingViolations = 0;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCORRECTED:
				table_entry->xdsl2ChAlarmConfProfileXturThresh15MinCorrected = table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCorrected;
				table_entry->old_xdsl2ChAlarmConfProfileXturThresh15MinCorrected = 0;
				break;
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2ChAlarmConfProfileTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2ChAlarmConfProfileRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2ChAlarmConfProfileRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2ChAlarmConfProfileTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
