/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef XDSL2SCALARSC_H
#define XDSL2SCALARSC_H

/* function declarations */
void init_xdsl2ScalarSC(void);
Netsnmp_Node_Handler handle_xdsl2ScalarSCMaxInterfaces;
Netsnmp_Node_Handler handle_xdsl2ScalarSCAvailInterfaces;

#endif /* XDSL2SCALARSC_H */
