/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2PMLineHist15MinTable.h"

/** Initializes the xdsl2PMLineHist15MinTable module */
void
init_xdsl2PMLineHist15MinTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2PMLineHist15MinTable();
}


/** Initialize the xdsl2PMLineHist15MinTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2PMLineHist15MinTable(void)
{
    const oid xdsl2PMLineHist15MinTable_oid[] = {1,3,6,1,2,1,10,251,1,4,1,3};
    const size_t xdsl2PMLineHist15MinTable_oid_len   = OID_LENGTH(xdsl2PMLineHist15MinTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2PMLineHist15MinTable:init", "initializing table xdsl2PMLineHist15MinTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2PMLineHist15MinTable",     xdsl2PMLineHist15MinTable_handler,
              xdsl2PMLineHist15MinTable_oid, xdsl2PMLineHist15MinTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2PMLHist15MUnit */
                           ASN_UNSIGNED,  /* index: xdsl2PMLHist15MInterval */
                           0);
    table_info->min_column = COLUMN_XDSL2PMLHIST15MMONITOREDTIME;
    table_info->max_column = COLUMN_XDSL2PMLHIST15MVALIDINTERVAL;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2PMLineHist15MinTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2PMLineHist15MinTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2PMLineHist15MinTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2PMLHist15MUnit;
    u_long xdsl2PMLHist15MInterval;

    /* Column values */
    u_long xdsl2PMLHist15MMonitoredTime;
    u_long xdsl2PMLHist15MFecs;
    u_long xdsl2PMLHist15MEs;
    u_long xdsl2PMLHist15MSes;
    u_long xdsl2PMLHist15MLoss;
    u_long xdsl2PMLHist15MUas;
    long xdsl2PMLHist15MValidInterval;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2PMLineHist15MinTable_entry *next;
};

struct xdsl2PMLineHist15MinTable_entry  *xdsl2PMLineHist15MinTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2PMLineHist15MinTable_entry *
xdsl2PMLineHist15MinTable_createEntry(long ifIndex, long xdsl2PMLHist15MUnit, u_long xdsl2PMLHist15MInterval) {
    struct xdsl2PMLineHist15MinTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2PMLineHist15MinTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2PMLHist15MUnit = xdsl2PMLHist15MUnit;
    entry->xdsl2PMLHist15MInterval = xdsl2PMLHist15MInterval;
    entry->next = xdsl2PMLineHist15MinTable_head;
    xdsl2PMLineHist15MinTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2PMLineHist15MinTable_removeEntry( struct xdsl2PMLineHist15MinTable_entry *entry ) {
    struct xdsl2PMLineHist15MinTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2PMLineHist15MinTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2PMLineHist15MinTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2PMLineHist15MinTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2PMLineHist15MinTable_head;
    return xdsl2PMLineHist15MinTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2PMLineHist15MinTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2PMLineHist15MinTable_entry *entry = (struct xdsl2PMLineHist15MinTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2PMLHist15MUnit );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->xdsl2PMLHist15MInterval );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2PMLineHist15MinTable table */
int
xdsl2PMLineHist15MinTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2PMLineHist15MinTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2PMLineHist15MinTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2PMLineHist15MinTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2PMLHIST15MMONITOREDTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLHist15MMonitoredTime);
                break;
            case COLUMN_XDSL2PMLHIST15MFECS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLHist15MFecs);
                break;
            case COLUMN_XDSL2PMLHIST15MES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLHist15MEs);
                break;
            case COLUMN_XDSL2PMLHIST15MSES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLHist15MSes);
                break;
            case COLUMN_XDSL2PMLHIST15MLOSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLHist15MLoss);
                break;
            case COLUMN_XDSL2PMLHIST15MUAS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLHist15MUas);
                break;
            case COLUMN_XDSL2PMLHIST15MVALIDINTERVAL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMLHist15MValidInterval);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
