/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */
#ifndef XDSL2NOTIFICATIONS_H
#define XDSL2NOTIFICATIONS_H

/* function declarations */
int send_xdsl2LinePerfFECSThreshXtuc_trap(void);
int send_xdsl2LinePerfFECSThreshXtur_trap(void);
int send_xdsl2LinePerfESThreshXtuc_trap(void);
int send_xdsl2LinePerfESThreshXtur_trap(void);
int send_xdsl2LinePerfSESThreshXtuc_trap(void);
int send_xdsl2LinePerfSESThreshXtur_trap(void);
int send_xdsl2LinePerfLOSSThreshXtuc_trap(void);
int send_xdsl2LinePerfLOSSThreshXtur_trap(void);
int send_xdsl2LinePerfUASThreshXtuc_trap(void);
int send_xdsl2LinePerfUASThreshXtur_trap(void);
int send_xdsl2LinePerfCodingViolationsThreshXtuc_trap(void);
int send_xdsl2LinePerfCodingViolationsThreshXtur_trap(void);
int send_xdsl2LinePerfCorrectedThreshXtuc_trap(void);
int send_xdsl2LinePerfCorrectedThreshXtur_trap(void);
int send_xdsl2LinePerfFailedFullInitThresh_trap(void);
int send_xdsl2LinePerfFailedShortInitThresh_trap(void);
int send_xdsl2LineStatusChangeXtuc_trap(void);
int send_xdsl2LineStatusChangeXtur_trap(void);

#endif /* XDSL2NOTIFICATIONS_H */
