/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2PMChHist1DTable.h"

/** Initializes the xdsl2PMChHist1DTable module */
void
init_xdsl2PMChHist1DTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2PMChHist1DTable();
}


/** Initialize the xdsl2PMChHist1DTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2PMChHist1DTable(void)
{
    const oid xdsl2PMChHist1DTable_oid[] = {1,3,6,1,2,1,10,251,1,4,2,3};
    const size_t xdsl2PMChHist1DTable_oid_len   = OID_LENGTH(xdsl2PMChHist1DTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2PMChHist1DTable:init", "initializing table xdsl2PMChHist1DTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2PMChHist1DTable",     xdsl2PMChHist1DTable_handler,
              xdsl2PMChHist1DTable_oid, xdsl2PMChHist1DTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2PMChHist1DUnit */
                           ASN_UNSIGNED,  /* index: xdsl2PMChHist1DInterval */
                           0);
    table_info->min_column = COLUMN_XDSL2PMCHHIST1DMONITOREDTIME;
    table_info->max_column = COLUMN_XDSL2PMCHHIST1DVALIDINTERVAL;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2PMChHist1DTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2PMChHist1DTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2PMChHist1DTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2PMChHist1DUnit;
    u_long xdsl2PMChHist1DInterval;

    /* Column values */
    u_long xdsl2PMChHist1DMonitoredTime;
    u_long xdsl2PMChHist1DCodingViolations;
    u_long xdsl2PMChHist1DCorrectedBlocks;
    long xdsl2PMChHist1DValidInterval;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2PMChHist1DTable_entry *next;
};

struct xdsl2PMChHist1DTable_entry  *xdsl2PMChHist1DTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2PMChHist1DTable_entry *
xdsl2PMChHist1DTable_createEntry(long ifIndex, long  xdsl2PMChHist1DUnit, u_long  xdsl2PMChHist1DInterval) {
    struct xdsl2PMChHist1DTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2PMChHist1DTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2PMChHist1DUnit = xdsl2PMChHist1DUnit;
    entry->xdsl2PMChHist1DInterval = xdsl2PMChHist1DInterval;
    entry->next = xdsl2PMChHist1DTable_head;
    xdsl2PMChHist1DTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2PMChHist1DTable_removeEntry( struct xdsl2PMChHist1DTable_entry *entry ) {
    struct xdsl2PMChHist1DTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2PMChHist1DTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2PMChHist1DTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2PMChHist1DTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2PMChHist1DTable_head;
    return xdsl2PMChHist1DTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2PMChHist1DTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2PMChHist1DTable_entry *entry = (struct xdsl2PMChHist1DTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2PMChHist1DUnit );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->xdsl2PMChHist1DInterval );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2PMChHist1DTable table */
int
xdsl2PMChHist1DTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2PMChHist1DTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2PMChHist1DTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2PMChHist1DTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2PMCHHIST1DMONITOREDTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChHist1DMonitoredTime);
                break;
            case COLUMN_XDSL2PMCHHIST1DCODINGVIOLATIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChHist1DCodingViolations);
                break;
            case COLUMN_XDSL2PMCHHIST1DCORRECTEDBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMChHist1DCorrectedBlocks);
                break;
            case COLUMN_XDSL2PMCHHIST1DVALIDINTERVAL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMChHist1DValidInterval);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
