/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineConfProfModeSpecBandUsTable.h"

 /** Initializes the xdsl2LineConfProfModeSpecBandUsTable module */
void
init_xdsl2LineConfProfModeSpecBandUsTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineConfProfModeSpecBandUsTable();
}


/** Initialize the xdsl2LineConfProfModeSpecBandUsTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineConfProfModeSpecBandUsTable(void)
{
	const oid xdsl2LineConfProfModeSpecBandUsTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,1,4 };
	const size_t xdsl2LineConfProfModeSpecBandUsTable_oid_len = OID_LENGTH(xdsl2LineConfProfModeSpecBandUsTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineConfProfModeSpecBandUsTable:init", "initializing table xdsl2LineConfProfModeSpecBandUsTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineConfProfModeSpecBandUsTable", xdsl2LineConfProfModeSpecBandUsTable_handler,
		xdsl2LineConfProfModeSpecBandUsTable_oid, xdsl2LineConfProfModeSpecBandUsTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LConfProfProfileName */
		ASN_INTEGER,  /* index: xdsl2LConfProfXdslMode */
		ASN_INTEGER,  /* index: xdsl2LConfProfXdslBandUs */
		0);
	table_info->min_column = COLUMN_XDSL2LCONFPROFUPBOPSDA;
	table_info->max_column = COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineConfProfModeSpecBandUsTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineConfProfModeSpecBandUsTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineConfProfModeSpecBandUsTable_entry {
	/* Index values */
	char xdsl2LConfProfProfileName[MAX_LEN_32];
	size_t xdsl2LConfProfProfileName_len;
	long xdsl2LConfProfXdslMode;
	long xdsl2LConfProfXdslBandUs;

	/* Column values */
	long xdsl2LConfProfUpboPsdA;
	long old_xdsl2LConfProfUpboPsdA;
	long xdsl2LConfProfUpboPsdB;
	long old_xdsl2LConfProfUpboPsdB;
	long xdsl2LConfProfModeSpecBandUsRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineConfProfModeSpecBandUsTable_entry* next;
};

struct xdsl2LineConfProfModeSpecBandUsTable_entry* xdsl2LineConfProfModeSpecBandUsTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineConfProfModeSpecBandUsTable_entry*
	xdsl2LineConfProfModeSpecBandUsTable_createEntry(
		unsigned char* xdsl2LConfProfProfileName,
		size_t xdsl2LConfProfProfileName_len,
		long  xdsl2LConfProfXdslMode,
		long  xdsl2LConfProfXdslBandUs) {
	struct xdsl2LineConfProfModeSpecBandUsTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineConfProfModeSpecBandUsTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LConfProfProfileName, xdsl2LConfProfProfileName, xdsl2LConfProfProfileName_len);
	entry->xdsl2LConfProfProfileName_len = xdsl2LConfProfProfileName_len;
	entry->xdsl2LConfProfXdslMode = xdsl2LConfProfXdslMode;
	entry->xdsl2LConfProfXdslBandUs = xdsl2LConfProfXdslBandUs;
	entry->next = xdsl2LineConfProfModeSpecBandUsTable_head;
	xdsl2LineConfProfModeSpecBandUsTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineConfProfModeSpecBandUsTable_removeEntry(struct xdsl2LineConfProfModeSpecBandUsTable_entry* entry) {
	struct xdsl2LineConfProfModeSpecBandUsTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineConfProfModeSpecBandUsTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineConfProfModeSpecBandUsTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineConfProfModeSpecBandUsTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineConfProfModeSpecBandUsTable_head;
	return xdsl2LineConfProfModeSpecBandUsTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineConfProfModeSpecBandUsTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineConfProfModeSpecBandUsTable_entry* entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LConfProfProfileName, sizeof(entry->xdsl2LConfProfProfileName));
		idx = idx->next_variable;
		snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->xdsl2LConfProfXdslMode);
		idx = idx->next_variable;
		snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->xdsl2LConfProfXdslBandUs);
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineConfProfModeSpecBandUsTable table */
int
xdsl2LineConfProfModeSpecBandUsTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineConfProfModeSpecBandUsTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineConfProfModeSpecBandUsTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFUPBOPSDA:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfUpboPsdA);
				break;
			case COLUMN_XDSL2LCONFPROFUPBOPSDB:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfUpboPsdB);
				break;
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfModeSpecBandUsRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFUPBOPSDA:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFUPBOPSDB:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineConfProfModeSpecBandUsTable_entry* table_row = xdsl2LineConfProfModeSpecBandUsTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len, *table_info->indexes->val.integer, *table_info->indexes->val.integer);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfProfModeSpecBandUsTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFUPBOPSDA:
				table_entry->old_xdsl2LConfProfUpboPsdA = table_entry->xdsl2LConfProfUpboPsdA;
				table_entry->xdsl2LConfProfUpboPsdA = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LCONFPROFUPBOPSDB:
				table_entry->old_xdsl2LConfProfUpboPsdB = table_entry->xdsl2LConfProfUpboPsdB;
				table_entry->xdsl2LConfProfUpboPsdB = *request->requestvb->val.integer;
				break;
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFUPBOPSDA:
				table_entry->xdsl2LConfProfUpboPsdA = table_entry->old_xdsl2LConfProfUpboPsdA;
				table_entry->old_xdsl2LConfProfUpboPsdA = 0;
				break;
			case COLUMN_XDSL2LCONFPROFUPBOPSDB:
				table_entry->xdsl2LConfProfUpboPsdB = table_entry->old_xdsl2LConfProfUpboPsdB;
				table_entry->old_xdsl2LConfProfUpboPsdB = 0;
				break;
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfProfModeSpecBandUsTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecBandUsTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECBANDUSROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2LConfProfModeSpecBandUsRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2LConfProfModeSpecBandUsRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2LineConfProfModeSpecBandUsTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
