/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2CHALARMCONFPROFILETABLE_H
#define XDSL2CHALARMCONFPROFILETABLE_H

#define MAX_PROFILE_NAME_LEN 32

/* function declarations */
void init_xdsl2ChAlarmConfProfileTable(void);
void initialize_table_xdsl2ChAlarmConfProfileTable(void);
Netsnmp_Node_Handler xdsl2ChAlarmConfProfileTable_handler;
Netsnmp_First_Data_Point  xdsl2ChAlarmConfProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2ChAlarmConfProfileTable_get_next_data_point;

/* column number definitions for table xdsl2ChAlarmConfProfileTable */
       #define COLUMN_XDSL2CHALARMCONFPROFILENAME		1
       #define COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCODINGVIOLATIONS		2
       #define COLUMN_XDSL2CHALARMCONFPROFILEXTUCTHRESH15MINCORRECTED		3
       #define COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCODINGVIOLATIONS		4
       #define COLUMN_XDSL2CHALARMCONFPROFILEXTURTHRESH15MINCORRECTED		5
       #define COLUMN_XDSL2CHALARMCONFPROFILEROWSTATUS		6
#endif /* XDSL2CHALARMCONFPROFILETABLE_H */
