/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineAlarmConfProfileTable.h"

 /** Initializes the xdsl2LineAlarmConfProfileTable module */
void
init_xdsl2LineAlarmConfProfileTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineAlarmConfProfileTable();
}


/** Initialize the xdsl2LineAlarmConfProfileTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineAlarmConfProfileTable(void)
{
	const oid xdsl2LineAlarmConfProfileTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,2 };
	const size_t xdsl2LineAlarmConfProfileTable_oid_len = OID_LENGTH(xdsl2LineAlarmConfProfileTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineAlarmConfProfileTable:init", "initializing table xdsl2LineAlarmConfProfileTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineAlarmConfProfileTable", xdsl2LineAlarmConfProfileTable_handler,
		xdsl2LineAlarmConfProfileTable_oid, xdsl2LineAlarmConfProfileTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LineAlarmConfProfileName */
		0);
	table_info->min_column = COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINFECS;
	table_info->max_column = COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineAlarmConfProfileTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineAlarmConfProfileTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineAlarmConfProfileTable_entry {
	/* Index values */
	char xdsl2LineAlarmConfProfileName[MAX_LEN_32];
	size_t xdsl2LineAlarmConfProfileName_len;

	/* Column values */
	u_long xdsl2LineAlarmConfProfileXtucThresh15MinFecs;
	u_long old_xdsl2LineAlarmConfProfileXtucThresh15MinFecs;
	u_long xdsl2LineAlarmConfProfileXtucThresh15MinEs;
	u_long old_xdsl2LineAlarmConfProfileXtucThresh15MinEs;
	u_long xdsl2LineAlarmConfProfileXtucThresh15MinSes;
	u_long old_xdsl2LineAlarmConfProfileXtucThresh15MinSes;
	u_long xdsl2LineAlarmConfProfileXtucThresh15MinLoss;
	u_long old_xdsl2LineAlarmConfProfileXtucThresh15MinLoss;
	u_long xdsl2LineAlarmConfProfileXtucThresh15MinUas;
	u_long old_xdsl2LineAlarmConfProfileXtucThresh15MinUas;
	u_long xdsl2LineAlarmConfProfileXturThresh15MinFecs;
	u_long old_xdsl2LineAlarmConfProfileXturThresh15MinFecs;
	u_long xdsl2LineAlarmConfProfileXturThresh15MinEs;
	u_long old_xdsl2LineAlarmConfProfileXturThresh15MinEs;
	u_long xdsl2LineAlarmConfProfileXturThresh15MinSes;
	u_long old_xdsl2LineAlarmConfProfileXturThresh15MinSes;
	u_long xdsl2LineAlarmConfProfileXturThresh15MinLoss;
	u_long old_xdsl2LineAlarmConfProfileXturThresh15MinLoss;
	u_long xdsl2LineAlarmConfProfileXturThresh15MinUas;
	u_long old_xdsl2LineAlarmConfProfileXturThresh15MinUas;
	u_long xdsl2LineAlarmConfProfileThresh15MinFailedFullInt;
	u_long old_xdsl2LineAlarmConfProfileThresh15MinFailedFullInt;
	u_long xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt;
	u_long old_xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt;
	long xdsl2LineAlarmConfProfileRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineAlarmConfProfileTable_entry* next;
};

struct xdsl2LineAlarmConfProfileTable_entry* xdsl2LineAlarmConfProfileTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineAlarmConfProfileTable_entry*
	xdsl2LineAlarmConfProfileTable_createEntry(
		unsigned char* xdsl2LineAlarmConfProfileName,
		size_t xdsl2LineAlarmConfProfileName_len) {
	struct xdsl2LineAlarmConfProfileTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineAlarmConfProfileTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LineAlarmConfProfileName, xdsl2LineAlarmConfProfileName, xdsl2LineAlarmConfProfileName_len);
	entry->xdsl2LineAlarmConfProfileName_len = xdsl2LineAlarmConfProfileName_len;
	entry->next = xdsl2LineAlarmConfProfileTable_head;
	xdsl2LineAlarmConfProfileTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineAlarmConfProfileTable_removeEntry(struct xdsl2LineAlarmConfProfileTable_entry* entry) {
	struct xdsl2LineAlarmConfProfileTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineAlarmConfProfileTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineAlarmConfProfileTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineAlarmConfProfileTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineAlarmConfProfileTable_head;
	return xdsl2LineAlarmConfProfileTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineAlarmConfProfileTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineAlarmConfProfileTable_entry* entry = (struct xdsl2LineAlarmConfProfileTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LineAlarmConfProfileName, sizeof(entry->xdsl2LineAlarmConfProfileName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineAlarmConfProfileTable table */
int
xdsl2LineAlarmConfProfileTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineAlarmConfProfileTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineAlarmConfProfileTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINFECS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinFecs);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINES:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinEs);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINSES:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinSes);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINLOSS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinLoss);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINUAS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinUas);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINFECS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXturThresh15MinFecs);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINES:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXturThresh15MinEs);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINSES:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXturThresh15MinSes);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINLOSS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXturThresh15MinLoss);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINUAS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileXturThresh15MinUas);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDFULLINT:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedFullInt);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDSHRTINT:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt);
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LineAlarmConfProfileRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINFECS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINES:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINSES:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINLOSS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINUAS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINFECS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINES:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINSES:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINLOSS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINUAS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDFULLINT:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDSHRTINT:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineAlarmConfProfileTable_entry* table_row = xdsl2LineAlarmConfProfileTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineAlarmConfProfileTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINFECS:
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinFecs = table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinFecs;
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinFecs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINES:
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinEs = table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinEs;
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinEs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINSES:
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinSes = table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinSes;
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinSes = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINLOSS:
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinLoss = table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinLoss;
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinLoss = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINUAS:
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinUas = table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinUas;
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinUas = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINFECS:
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinFecs = table_entry->xdsl2LineAlarmConfProfileXturThresh15MinFecs;
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinFecs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINES:
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinEs = table_entry->xdsl2LineAlarmConfProfileXturThresh15MinEs;
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinEs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINSES:
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinSes = table_entry->xdsl2LineAlarmConfProfileXturThresh15MinSes;
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinSes = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINLOSS:
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinLoss = table_entry->xdsl2LineAlarmConfProfileXturThresh15MinLoss;
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinLoss = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINUAS:
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinUas = table_entry->xdsl2LineAlarmConfProfileXturThresh15MinUas;
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinUas = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDFULLINT:
				table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedFullInt = table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedFullInt;
				table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedFullInt = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDSHRTINT:
				table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt = table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt;
				table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt = *request->requestvb->val.integer;
				break;
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINFECS:
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinFecs = table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinFecs;
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinFecs = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINES:
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinEs = table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinEs;
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinEs = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINSES:
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinSes = table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinSes;
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinSes = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINLOSS:
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinLoss = table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinLoss;
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinLoss = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTUCTHRESH15MINUAS:
				table_entry->xdsl2LineAlarmConfProfileXtucThresh15MinUas = table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinUas;
				table_entry->old_xdsl2LineAlarmConfProfileXtucThresh15MinUas = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINFECS:
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinFecs = table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinFecs;
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinFecs = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINES:
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinEs = table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinEs;
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinEs = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINSES:
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinSes = table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinSes;
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinSes = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINLOSS:
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinLoss = table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinLoss;
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinLoss = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEXTURTHRESH15MINUAS:
				table_entry->xdsl2LineAlarmConfProfileXturThresh15MinUas = table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinUas;
				table_entry->old_xdsl2LineAlarmConfProfileXturThresh15MinUas = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDFULLINT:
				table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedFullInt = table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedFullInt;
				table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedFullInt = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILETHRESH15MINFAILEDSHRTINT:
				table_entry->xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt = table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt;
				table_entry->old_xdsl2LineAlarmConfProfileThresh15MinFailedShrtInt = 0;
				break;
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineAlarmConfProfileTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LINEALARMCONFPROFILEROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2LineAlarmConfProfileRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2LineAlarmConfProfileRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2LineAlarmConfProfileTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
