/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineConfProfModeSpecTable.h"

 /** Initializes the xdsl2LineConfProfModeSpecTable module */
void
init_xdsl2LineConfProfModeSpecTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineConfProfModeSpecTable();
}


/** Initialize the xdsl2LineConfProfModeSpecTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineConfProfModeSpecTable(void)
{
	const oid xdsl2LineConfProfModeSpecTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,1,3 };
	const size_t xdsl2LineConfProfModeSpecTable_oid_len = OID_LENGTH(xdsl2LineConfProfModeSpecTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineConfProfModeSpecTable:init", "initializing table xdsl2LineConfProfModeSpecTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineConfProfModeSpecTable", xdsl2LineConfProfModeSpecTable_handler,
		xdsl2LineConfProfModeSpecTable_oid, xdsl2LineConfProfModeSpecTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LConfProfProfileName */
		ASN_INTEGER,  /* index: xdsl2LConfProfXdslMode */
		0);
	table_info->min_column = COLUMN_XDSL2LCONFPROFMAXNOMPSDDS;
	table_info->max_column = COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineConfProfModeSpecTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineConfProfModeSpecTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineConfProfModeSpecTable_entry {
	/* Index values */
	char xdsl2LConfProfProfileName[MAX_LEN_32];
	size_t xdsl2LConfProfProfileName_len;
	long xdsl2LConfProfXdslMode;

	/* Column values */
	long xdsl2LConfProfMaxNomPsdDs;
	long old_xdsl2LConfProfMaxNomPsdDs;
	long xdsl2LConfProfMaxNomPsdUs;
	long old_xdsl2LConfProfMaxNomPsdUs;
	u_long xdsl2LConfProfMaxNomAtpDs;
	u_long old_xdsl2LConfProfMaxNomAtpDs;
	u_long xdsl2LConfProfMaxNomAtpUs;
	u_long old_xdsl2LConfProfMaxNomAtpUs;
	long xdsl2LConfProfMaxAggRxPwrUs;
	long old_xdsl2LConfProfMaxAggRxPwrUs;
	long xdsl2LConfProfPsdMaskDs;
	long old_xdsl2LConfProfPsdMaskDs;
	long xdsl2LConfProfPsdMaskUs;
	long old_xdsl2LConfProfPsdMaskUs;
	long xdsl2LConfProfPsdMaskSelectUs;
	long old_xdsl2LConfProfPsdMaskSelectUs;
	long xdsl2LConfProfClassMask;
	long old_xdsl2LConfProfClassMask;
	char xdsl2LConfProfLimitMask[MAX_LEN_32];
	size_t xdsl2LConfProfLimitMask_len;
	char old_xdsl2LConfProfLimitMask[MAX_LEN_32];
	size_t old_xdsl2LConfProfLimitMask_len;
	char xdsl2LConfProfUs0Disable[MAX_LEN_32];
	size_t xdsl2LConfProfUs0Disable_len;
	char old_xdsl2LConfProfUs0Disable[MAX_LEN_32];
	size_t old_xdsl2LConfProfUs0Disable_len;
	long xdsl2LConfProfModeSpecRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineConfProfModeSpecTable_entry* next;
};

struct xdsl2LineConfProfModeSpecTable_entry* xdsl2LineConfProfModeSpecTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineConfProfModeSpecTable_entry*
	xdsl2LineConfProfModeSpecTable_createEntry(unsigned char* xdsl2LConfProfProfileName, size_t xdsl2LConfProfProfileName_len, long  xdsl2LConfProfXdslMode) {
	struct xdsl2LineConfProfModeSpecTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineConfProfModeSpecTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LConfProfProfileName, xdsl2LConfProfProfileName, xdsl2LConfProfProfileName_len);
	entry->xdsl2LConfProfProfileName_len = xdsl2LConfProfProfileName_len;
	entry->xdsl2LConfProfXdslMode = xdsl2LConfProfXdslMode;
	entry->next = xdsl2LineConfProfModeSpecTable_head;
	xdsl2LineConfProfModeSpecTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineConfProfModeSpecTable_removeEntry(struct xdsl2LineConfProfModeSpecTable_entry* entry) {
	struct xdsl2LineConfProfModeSpecTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineConfProfModeSpecTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineConfProfModeSpecTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineConfProfModeSpecTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineConfProfModeSpecTable_head;
	return xdsl2LineConfProfModeSpecTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineConfProfModeSpecTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineConfProfModeSpecTable_entry* entry = (struct xdsl2LineConfProfModeSpecTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LConfProfProfileName, sizeof(entry->xdsl2LConfProfProfileName));
		idx = idx->next_variable;
		snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->xdsl2LConfProfXdslMode);
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineConfProfModeSpecTable table */
int
xdsl2LineConfProfModeSpecTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineConfProfModeSpecTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineConfProfModeSpecTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMAXNOMPSDDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfMaxNomPsdDs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMPSDUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfMaxNomPsdUs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMATPDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMaxNomAtpDs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMATPUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2LConfProfMaxNomAtpUs);
				break;
			case COLUMN_XDSL2LCONFPROFMAXAGGRXPWRUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfMaxAggRxPwrUs);
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfPsdMaskDs, sizeof(table_entry->xdsl2LConfProfPsdMaskDs));
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_INTEGER, &table_entry->xdsl2LConfProfPsdMaskUs, sizeof(table_entry->xdsl2LConfProfPsdMaskUs));
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKSELECTUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfPsdMaskSelectUs);
				break;
			case COLUMN_XDSL2LCONFPROFCLASSMASK:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfClassMask);
				break;
			case COLUMN_XDSL2LCONFPROFLIMITMASK:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfLimitMask,
					table_entry->xdsl2LConfProfLimitMask_len);
				break;
			case COLUMN_XDSL2LCONFPROFUS0DISABLE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LConfProfUs0Disable,
					table_entry->xdsl2LConfProfUs0Disable_len);
				break;
			case COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LConfProfModeSpecRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMAXNOMPSDDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMPSDUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMATPDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXNOMATPUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMAXAGGRXPWRUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKDS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfPsdMaskDs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKUS:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfPsdMaskUs));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFPSDMASKSELECTUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFCLASSMASK:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFLIMITMASK:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfLimitMask));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFUS0DISABLE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LConfProfUs0Disable));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineConfProfModeSpecTable_entry* table_row = xdsl2LineConfProfModeSpecTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len, *table_info->indexes->val.integer);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineConfProfModeSpecTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LCONFPROFMODESPECROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineConfProfModeSpecTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
