/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2PMLineCurrTable.h"

/** Initializes the xdsl2PMLineCurrTable module */
void
init_xdsl2PMLineCurrTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2PMLineCurrTable();
}


/** Initialize the xdsl2PMLineCurrTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2PMLineCurrTable(void)
{
    const oid xdsl2PMLineCurrTable_oid[] = {1,3,6,1,2,1,10,251,1,4,1,1};
    const size_t xdsl2PMLineCurrTable_oid_len   = OID_LENGTH(xdsl2PMLineCurrTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2PMLineCurrTable:init", "initializing table xdsl2PMLineCurrTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2PMLineCurrTable",     xdsl2PMLineCurrTable_handler,
              xdsl2PMLineCurrTable_oid, xdsl2PMLineCurrTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2PMLCurrUnit */
                           0);
    table_info->min_column = COLUMN_XDSL2PMLCURR15MVALIDINTERVALS;
    table_info->max_column = COLUMN_XDSL2PMLCURR1DAYUAS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2PMLineCurrTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2PMLineCurrTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2PMLineCurrTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2PMLCurrUnit;

    /* Column values */
    u_long xdsl2PMLCurr15MValidIntervals;
    u_long xdsl2PMLCurr15MInvalidIntervals;
    long xdsl2PMLCurr15MTimeElapsed;
    u_long xdsl2PMLCurr15MFecs;
    u_long xdsl2PMLCurr15MEs;
    u_long xdsl2PMLCurr15MSes;
    u_long xdsl2PMLCurr15MLoss;
    u_long xdsl2PMLCurr15MUas;
    u_long xdsl2PMLCurr1DayValidIntervals;
    u_long xdsl2PMLCurr1DayInvalidIntervals;
    long xdsl2PMLCurr1DayTimeElapsed;
    u_long xdsl2PMLCurr1DayFecs;
    u_long xdsl2PMLCurr1DayEs;
    u_long xdsl2PMLCurr1DaySes;
    u_long xdsl2PMLCurr1DayLoss;
    u_long xdsl2PMLCurr1DayUas;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2PMLineCurrTable_entry *next;
};

struct xdsl2PMLineCurrTable_entry  *xdsl2PMLineCurrTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2PMLineCurrTable_entry *
xdsl2PMLineCurrTable_createEntry(long ifIndex, long xdsl2PMLCurrUnit) {
    struct xdsl2PMLineCurrTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2PMLineCurrTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2PMLCurrUnit = xdsl2PMLCurrUnit;
    entry->next = xdsl2PMLineCurrTable_head;
    xdsl2PMLineCurrTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2PMLineCurrTable_removeEntry( struct xdsl2PMLineCurrTable_entry *entry ) {
    struct xdsl2PMLineCurrTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2PMLineCurrTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2PMLineCurrTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2PMLineCurrTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2PMLineCurrTable_head;
    return xdsl2PMLineCurrTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2PMLineCurrTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2PMLineCurrTable_entry *entry = (struct xdsl2PMLineCurrTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2PMLCurrUnit );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2PMLineCurrTable table */
int
xdsl2PMLineCurrTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2PMLineCurrTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2PMLineCurrTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2PMLineCurrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2PMLCURR15MVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLCurr15MValidIntervals);
                break;
            case COLUMN_XDSL2PMLCURR15MINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLCurr15MInvalidIntervals);
                break;
            case COLUMN_XDSL2PMLCURR15MTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMLCurr15MTimeElapsed);
                break;
            case COLUMN_XDSL2PMLCURR15MFECS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr15MFecs);
                break;
            case COLUMN_XDSL2PMLCURR15MES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr15MEs);
                break;
            case COLUMN_XDSL2PMLCURR15MSES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr15MSes);
                break;
            case COLUMN_XDSL2PMLCURR15MLOSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr15MLoss);
                break;
            case COLUMN_XDSL2PMLCURR15MUAS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr15MUas);
                break;
            case COLUMN_XDSL2PMLCURR1DAYVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLCurr1DayValidIntervals);
                break;
            case COLUMN_XDSL2PMLCURR1DAYINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLCurr1DayInvalidIntervals);
                break;
            case COLUMN_XDSL2PMLCURR1DAYTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2PMLCurr1DayTimeElapsed);
                break;
            case COLUMN_XDSL2PMLCURR1DAYFECS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr1DayFecs);
                break;
            case COLUMN_XDSL2PMLCURR1DAYES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr1DayEs);
                break;
            case COLUMN_XDSL2PMLCURR1DAYSES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr1DaySes);
                break;
            case COLUMN_XDSL2PMLCURR1DAYLOSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr1DayLoss);
                break;
            case COLUMN_XDSL2PMLCURR1DAYUAS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->xdsl2PMLCurr1DayUas);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
