/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineBandTable.h"

/** Initializes the xdsl2LineBandTable module */
void
init_xdsl2LineBandTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2LineBandTable();
}


/** Initialize the xdsl2LineBandTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineBandTable(void)
{
    const oid xdsl2LineBandTable_oid[] = {1,3,6,1,2,1,10,251,1,1,2};
    const size_t xdsl2LineBandTable_oid_len   = OID_LENGTH(xdsl2LineBandTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2LineBandTable:init", "initializing table xdsl2LineBandTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2LineBandTable",     xdsl2LineBandTable_handler,
              xdsl2LineBandTable_oid, xdsl2LineBandTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           ASN_INTEGER,  /* index: xdsl2LineBand */
                           0);
    table_info->min_column = COLUMN_XDSL2LINEBANDSTATUSLNATTEN;
    table_info->max_column = COLUMN_XDSL2LINEBANDSTATUSSNRMARGIN;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2LineBandTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2LineBandTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2LineBandTable_entry {
    /* Index values */
    long ifIndex;
    long xdsl2LineBand;

    /* Column values */
    u_long xdsl2LineBandStatusLnAtten;
    u_long xdsl2LineBandStatusSigAtten;
    long xdsl2LineBandStatusSnrMargin;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2LineBandTable_entry *next;
};

struct xdsl2LineBandTable_entry  *xdsl2LineBandTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineBandTable_entry *
xdsl2LineBandTable_createEntry(long ifIndex, long xdsl2LineBand) {
    struct xdsl2LineBandTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineBandTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->xdsl2LineBand = xdsl2LineBand;
    entry->next = xdsl2LineBandTable_head;
    xdsl2LineBandTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2LineBandTable_removeEntry( struct xdsl2LineBandTable_entry *entry ) {
    struct xdsl2LineBandTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2LineBandTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2LineBandTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2LineBandTable_get_first_data_point(void **my_loop_context, void **my_data_context, netsnmp_variable_list *put_index_data, netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2LineBandTable_head;
    return xdsl2LineBandTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2LineBandTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2LineBandTable_entry *entry = (struct xdsl2LineBandTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xdsl2LineBand );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2LineBandTable table */
int
xdsl2LineBandTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2LineBandTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2LineBandTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2LineBandTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2LINEBANDSTATUSLNATTEN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2LineBandStatusLnAtten);
                break;
            case COLUMN_XDSL2LINEBANDSTATUSSIGATTEN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2LineBandStatusSigAtten);
                break;
            case COLUMN_XDSL2LINEBANDSTATUSSNRMARGIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xdsl2LineBandStatusSnrMargin);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
