/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMCHCURRTABLE_H
#define XDSL2PMCHCURRTABLE_H

/* function declarations */
void init_xdsl2PMChCurrTable(void);
void initialize_table_xdsl2PMChCurrTable(void);
Netsnmp_Node_Handler xdsl2PMChCurrTable_handler;
Netsnmp_First_Data_Point  xdsl2PMChCurrTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMChCurrTable_get_next_data_point;

/* column number definitions for table xdsl2PMChCurrTable */
       #define COLUMN_XDSL2PMCHCURRUNIT		1
       #define COLUMN_XDSL2PMCHCURR15MVALIDINTERVALS		2
       #define COLUMN_XDSL2PMCHCURR15MINVALIDINTERVALS		3
       #define COLUMN_XDSL2PMCHCURR15MTIMEELAPSED		4
       #define COLUMN_XDSL2PMCHCURR15MCODINGVIOLATIONS		5
       #define COLUMN_XDSL2PMCHCURR15MCORRECTEDBLOCKS		6
       #define COLUMN_XDSL2PMCHCURR1DAYVALIDINTERVALS		7
       #define COLUMN_XDSL2PMCHCURR1DAYINVALIDINTERVALS		8
       #define COLUMN_XDSL2PMCHCURR1DAYTIMEELAPSED		9
       #define COLUMN_XDSL2PMCHCURR1DAYCODINGVIOLATIONS		10
       #define COLUMN_XDSL2PMCHCURR1DAYCORRECTEDBLOCKS		11
#endif /* XDSL2PMCHCURRTABLE_H */
