/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2PMLineInitCurrTable.h"

/** Initializes the xdsl2PMLineInitCurrTable module */
void
init_xdsl2PMLineInitCurrTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xdsl2PMLineInitCurrTable();
}


/** Initialize the xdsl2PMLineInitCurrTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2PMLineInitCurrTable(void)
{
    const oid xdsl2PMLineInitCurrTable_oid[] = {1,3,6,1,2,1,10,251,1,4,1,2};
    const size_t xdsl2PMLineInitCurrTable_oid_len   = OID_LENGTH(xdsl2PMLineInitCurrTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("xdsl2PMLineInitCurrTable:init", "initializing table xdsl2PMLineInitCurrTable\n"));

    reg = netsnmp_create_handler_registration(
              "xdsl2PMLineInitCurrTable",     xdsl2PMLineInitCurrTable_handler,
              xdsl2PMLineInitCurrTable_oid, xdsl2PMLineInitCurrTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           0);
    table_info->min_column = COLUMN_XDSL2PMLINITCURR15MVALIDINTERVALS;
    table_info->max_column = COLUMN_XDSL2PMLINITCURR1DAYFAILEDSHORTINITS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xdsl2PMLineInitCurrTable_get_first_data_point;
    iinfo->get_next_data_point  = xdsl2PMLineInitCurrTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xdsl2PMLineInitCurrTable_entry {
    /* Index values */
    long ifIndex;

    /* Column values */
    u_long xdsl2PMLInitCurr15MValidIntervals;
    u_long xdsl2PMLInitCurr15MInvalidIntervals;
    u_long xdsl2PMLInitCurr15MTimeElapsed;
    u_long xdsl2PMLInitCurr15MFullInits;
    u_long xdsl2PMLInitCurr15MFailedFullInits;
    u_long xdsl2PMLInitCurr15MShortInits;
    u_long xdsl2PMLInitCurr15MFailedShortInits;
    u_long xdsl2PMLInitCurr1DayValidIntervals;
    u_long xdsl2PMLInitCurr1DayInvalidIntervals;
    u_long xdsl2PMLInitCurr1DayTimeElapsed;
    u_long xdsl2PMLInitCurr1DayFullInits;
    u_long xdsl2PMLInitCurr1DayFailedFullInits;
    u_long xdsl2PMLInitCurr1DayShortInits;
    u_long xdsl2PMLInitCurr1DayFailedShortInits;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xdsl2PMLineInitCurrTable_entry *next;
};

struct xdsl2PMLineInitCurrTable_entry  *xdsl2PMLineInitCurrTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2PMLineInitCurrTable_entry *
xdsl2PMLineInitCurrTable_createEntry(long ifIndex) {
    struct xdsl2PMLineInitCurrTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xdsl2PMLineInitCurrTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->next = xdsl2PMLineInitCurrTable_head;
    xdsl2PMLineInitCurrTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xdsl2PMLineInitCurrTable_removeEntry( struct xdsl2PMLineInitCurrTable_entry *entry ) {
    struct xdsl2PMLineInitCurrTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xdsl2PMLineInitCurrTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xdsl2PMLineInitCurrTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xdsl2PMLineInitCurrTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xdsl2PMLineInitCurrTable_head;
    return xdsl2PMLineInitCurrTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xdsl2PMLineInitCurrTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xdsl2PMLineInitCurrTable_entry *entry = (struct xdsl2PMLineInitCurrTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xdsl2PMLineInitCurrTable table */
int
xdsl2PMLineInitCurrTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xdsl2PMLineInitCurrTable_entry          *table_entry;

    DEBUGMSGTL(("xdsl2PMLineInitCurrTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xdsl2PMLineInitCurrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XDSL2PMLINITCURR15MVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MValidIntervals);
                break;
            case COLUMN_XDSL2PMLINITCURR15MINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MInvalidIntervals);
                break;
            case COLUMN_XDSL2PMLINITCURR15MTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MTimeElapsed);
                break;
            case COLUMN_XDSL2PMLINITCURR15MFULLINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MFullInits);
                break;
            case COLUMN_XDSL2PMLINITCURR15MFAILEDFULLINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MFailedFullInits);
                break;
            case COLUMN_XDSL2PMLINITCURR15MSHORTINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MShortInits);
                break;
            case COLUMN_XDSL2PMLINITCURR15MFAILEDSHORTINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr15MFailedShortInits);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayValidIntervals);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYINVALIDINTERVALS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayInvalidIntervals);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYTIMEELAPSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayTimeElapsed);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYFULLINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayFullInits);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYFAILEDFULLINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayFailedFullInits);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYSHORTINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayShortInits);
                break;
            case COLUMN_XDSL2PMLINITCURR1DAYFAILEDSHORTINITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->xdsl2PMLInitCurr1DayFailedShortInits);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
