/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2SCSTATUSTABLE_H
#define XDSL2SCSTATUSTABLE_H

/* function declarations */
void init_xdsl2SCStatusTable(void);
void initialize_table_xdsl2SCStatusTable(void);
Netsnmp_Node_Handler xdsl2SCStatusTable_handler;
Netsnmp_First_Data_Point  xdsl2SCStatusTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2SCStatusTable_get_next_data_point;

/* column number definitions for table xdsl2SCStatusTable */
       #define COLUMN_XDSL2SCSTATUSDIRECTION		1
       #define COLUMN_XDSL2SCSTATUSLINSCALE		2
       #define COLUMN_XDSL2SCSTATUSLINSCGROUPSIZE		3
       #define COLUMN_XDSL2SCSTATUSLOGMT		4
       #define COLUMN_XDSL2SCSTATUSLOGSCGROUPSIZE		5
       #define COLUMN_XDSL2SCSTATUSQLNMT		6
       #define COLUMN_XDSL2SCSTATUSQLNSCGROUPSIZE		7
       #define COLUMN_XDSL2SCSTATUSSNRMTIME		8
       #define COLUMN_XDSL2SCSTATUSSNRSCGROUPSIZE		9
       #define COLUMN_XDSL2SCSTATUSATTAINABLERATE		10
       #define COLUMN_XDSL2SCSTATUSROWSTATUS		11
#endif /* XDSL2SCSTATUSTABLE_H */
