/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2SCSTATUSSEGMENTTABLE_H
#define XDSL2SCSTATUSSEGMENTTABLE_H

#define MAX_LEN_1024 1024
#define MAX_LEN_512 512
#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2SCStatusSegmentTable(void);
void initialize_table_xdsl2SCStatusSegmentTable(void);
Netsnmp_Node_Handler xdsl2SCStatusSegmentTable_handler;
Netsnmp_First_Data_Point  xdsl2SCStatusSegmentTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2SCStatusSegmentTable_get_next_data_point;

/* column number definitions for table xdsl2SCStatusSegmentTable */
       #define COLUMN_XDSL2SCSTATUSSEGMENT		1
       #define COLUMN_XDSL2SCSTATUSSEGMENTLINREAL		2
       #define COLUMN_XDSL2SCSTATUSSEGMENTLINIMG		3
       #define COLUMN_XDSL2SCSTATUSSEGMENTLOG		4
       #define COLUMN_XDSL2SCSTATUSSEGMENTQLN		5
       #define COLUMN_XDSL2SCSTATUSSEGMENTSNR		6
       #define COLUMN_XDSL2SCSTATUSSEGMENTBITSALLOC		7
       #define COLUMN_XDSL2SCSTATUSSEGMENTGAINALLOC		8
#endif /* XDSL2SCSTATUSSEGMENTTABLE_H */
