/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMLINEINITHIST15MINTABLE_H
#define XDSL2PMLINEINITHIST15MINTABLE_H

/* function declarations */
void init_xdsl2PMLineInitHist15MinTable(void);
void initialize_table_xdsl2PMLineInitHist15MinTable(void);
Netsnmp_Node_Handler xdsl2PMLineInitHist15MinTable_handler;
Netsnmp_First_Data_Point  xdsl2PMLineInitHist15MinTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMLineInitHist15MinTable_get_next_data_point;

/* column number definitions for table xdsl2PMLineInitHist15MinTable */
       #define COLUMN_XDSL2PMLINITHIST15MINTERVAL		1
       #define COLUMN_XDSL2PMLINITHIST15MMONITOREDTIME		2
       #define COLUMN_XDSL2PMLINITHIST15MFULLINITS		3
       #define COLUMN_XDSL2PMLINITHIST15MFAILEDFULLINITS		4
       #define COLUMN_XDSL2PMLINITHIST15MSHORTINITS		5
       #define COLUMN_XDSL2PMLINITHIST15MFAILEDSHORTINITS		6
       #define COLUMN_XDSL2PMLINITHIST15MVALIDINTERVAL		7
#endif /* XDSL2PMLINEINITHIST15MINTABLE_H */
