/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINECONFTEMPLATETABLE_H
#define XDSL2LINECONFTEMPLATETABLE_H

#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineConfTemplateTable(void);
void initialize_table_xdsl2LineConfTemplateTable(void);
Netsnmp_Node_Handler xdsl2LineConfTemplateTable_handler;
Netsnmp_First_Data_Point  xdsl2LineConfTemplateTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineConfTemplateTable_get_next_data_point;

/* column number definitions for table xdsl2LineConfTemplateTable */
       #define COLUMN_XDSL2LCONFTEMPTEMPLATENAME		1
       #define COLUMN_XDSL2LCONFTEMPLINEPROFILE		2
       #define COLUMN_XDSL2LCONFTEMPCHAN1CONFPROFILE		3
       #define COLUMN_XDSL2LCONFTEMPCHAN1RARATIODS		4
       #define COLUMN_XDSL2LCONFTEMPCHAN1RARATIOUS		5
       #define COLUMN_XDSL2LCONFTEMPCHAN2CONFPROFILE		6
       #define COLUMN_XDSL2LCONFTEMPCHAN2RARATIODS		7
       #define COLUMN_XDSL2LCONFTEMPCHAN2RARATIOUS		8
       #define COLUMN_XDSL2LCONFTEMPCHAN3CONFPROFILE		9
       #define COLUMN_XDSL2LCONFTEMPCHAN3RARATIODS		10
       #define COLUMN_XDSL2LCONFTEMPCHAN3RARATIOUS		11
       #define COLUMN_XDSL2LCONFTEMPCHAN4CONFPROFILE		12
       #define COLUMN_XDSL2LCONFTEMPCHAN4RARATIODS		13
       #define COLUMN_XDSL2LCONFTEMPCHAN4RARATIOUS		14
       #define COLUMN_XDSL2LCONFTEMPROWSTATUS		15
#endif /* XDSL2LINECONFTEMPLATETABLE_H */
