/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2ScalarSC.h"

/** Initializes the xdsl2ScalarSC module */
void
init_xdsl2ScalarSC(void)
{
    const oid xdsl2ScalarSCMaxInterfaces_oid[] = { 1,3,6,1,2,1,10,251,1,6,1,1 };
    const oid xdsl2ScalarSCAvailInterfaces_oid[] = { 1,3,6,1,2,1,10,251,1,6,1,2 };

  DEBUGMSGTL(("xdsl2ScalarSC", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("xdsl2ScalarSCMaxInterfaces", handle_xdsl2ScalarSCMaxInterfaces,
                               xdsl2ScalarSCMaxInterfaces_oid, OID_LENGTH(xdsl2ScalarSCMaxInterfaces_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("xdsl2ScalarSCAvailInterfaces", handle_xdsl2ScalarSCAvailInterfaces,
                               xdsl2ScalarSCAvailInterfaces_oid, OID_LENGTH(xdsl2ScalarSCAvailInterfaces_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_xdsl2ScalarSCMaxInterfaces(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    static uint32_t maxInterfaces = 32;

    switch(reqinfo->mode) {

        case MODE_GET:
            //TODO:
            snmp_set_var_typed_value(requests->requestvb, ASN_UNSIGNED,
                                     (u_char*)&maxInterfaces/* XXX: a pointer to the scalar's data */,
                                     sizeof(maxInterfaces)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_xdsl2ScalarSCMaxInterfaces\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_xdsl2ScalarSCAvailInterfaces(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    static uint32_t availInterfaces = 0;

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_UNSIGNED,
                                     (u_char*)&availInterfaces/* XXX: a pointer to the scalar's data */,
                                     sizeof(availInterfaces)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_xdsl2ScalarSCAvailInterfaces\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
