/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2LineAlarmConfTemplateTable.h"

 /** Initializes the xdsl2LineAlarmConfTemplateTable module */
void
init_xdsl2LineAlarmConfTemplateTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2LineAlarmConfTemplateTable();
}


/** Initialize the xdsl2LineAlarmConfTemplateTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2LineAlarmConfTemplateTable(void)
{
	const oid xdsl2LineAlarmConfTemplateTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,3,1 };
	const size_t xdsl2LineAlarmConfTemplateTable_oid_len = OID_LENGTH(xdsl2LineAlarmConfTemplateTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2LineAlarmConfTemplateTable:init", "initializing table xdsl2LineAlarmConfTemplateTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2LineAlarmConfTemplateTable", xdsl2LineAlarmConfTemplateTable_handler,
		xdsl2LineAlarmConfTemplateTable_oid, xdsl2LineAlarmConfTemplateTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2LAlarmConfTempTemplateName */
		0);
	table_info->min_column = COLUMN_XDSL2LALARMCONFTEMPLINEPROFILE;
	table_info->max_column = COLUMN_XDSL2LALARMCONFTEMPROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2LineAlarmConfTemplateTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2LineAlarmConfTemplateTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2LineAlarmConfTemplateTable_entry {
	/* Index values */
	char xdsl2LAlarmConfTempTemplateName[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempTemplateName_len;

	/* Column values */
	char xdsl2LAlarmConfTempLineProfile[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempLineProfile_len;
	char xdsl2LAlarmConfTempChan1ConfProfile[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempChan1ConfProfile_len;
	char xdsl2LAlarmConfTempChan2ConfProfile[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempChan2ConfProfile_len;
	char xdsl2LAlarmConfTempChan3ConfProfile[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempChan3ConfProfile_len;
	char xdsl2LAlarmConfTempChan4ConfProfile[MAX_LEN_32];
	size_t xdsl2LAlarmConfTempChan4ConfProfile_len;
	long xdsl2LAlarmConfTempRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2LineAlarmConfTemplateTable_entry* next;
};

struct xdsl2LineAlarmConfTemplateTable_entry* xdsl2LineAlarmConfTemplateTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2LineAlarmConfTemplateTable_entry*
	xdsl2LineAlarmConfTemplateTable_createEntry(unsigned char* xdsl2LAlarmConfTempTemplateName,
		size_t xdsl2LAlarmConfTempTemplateName_len) {
	struct xdsl2LineAlarmConfTemplateTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2LineAlarmConfTemplateTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2LAlarmConfTempTemplateName, xdsl2LAlarmConfTempTemplateName, xdsl2LAlarmConfTempTemplateName_len);
	entry->xdsl2LAlarmConfTempTemplateName_len = xdsl2LAlarmConfTempTemplateName_len;
	entry->next = xdsl2LineAlarmConfTemplateTable_head;
	xdsl2LineAlarmConfTemplateTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2LineAlarmConfTemplateTable_removeEntry(struct xdsl2LineAlarmConfTemplateTable_entry* entry) {
	struct xdsl2LineAlarmConfTemplateTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2LineAlarmConfTemplateTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2LineAlarmConfTemplateTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2LineAlarmConfTemplateTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2LineAlarmConfTemplateTable_head;
	return xdsl2LineAlarmConfTemplateTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2LineAlarmConfTemplateTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2LineAlarmConfTemplateTable_entry* entry = (struct xdsl2LineAlarmConfTemplateTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2LAlarmConfTempTemplateName, sizeof(entry->xdsl2LAlarmConfTempTemplateName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2LineAlarmConfTemplateTable table */
int
xdsl2LineAlarmConfTemplateTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2LineAlarmConfTemplateTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2LineAlarmConfTemplateTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LALARMCONFTEMPLINEPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LAlarmConfTempLineProfile,
					table_entry->xdsl2LAlarmConfTempLineProfile_len);
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN1CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LAlarmConfTempChan1ConfProfile,
					table_entry->xdsl2LAlarmConfTempChan1ConfProfile_len);
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN2CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LAlarmConfTempChan2ConfProfile,
					table_entry->xdsl2LAlarmConfTempChan2ConfProfile_len);
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN3CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LAlarmConfTempChan3ConfProfile,
					table_entry->xdsl2LAlarmConfTempChan3ConfProfile_len);
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN4CONFPROFILE:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
					table_entry->xdsl2LAlarmConfTempChan4ConfProfile,
					table_entry->xdsl2LAlarmConfTempChan4ConfProfile_len);
				break;
			case COLUMN_XDSL2LALARMCONFTEMPROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2LAlarmConfTempRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2LALARMCONFTEMPLINEPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LAlarmConfTempLineProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN1CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LAlarmConfTempChan1ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN2CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LAlarmConfTempChan2ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN3CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LAlarmConfTempChan3ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LALARMCONFTEMPCHAN4CONFPROFILE:
				/* or possibly 'netsnmp_check_vb_type_and_size' */
				ret = netsnmp_check_vb_type_and_max_size(
					request->requestvb, ASN_OCTET_STR, sizeof(table_entry->xdsl2LAlarmConfTempChan4ConfProfile));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2LALARMCONFTEMPROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LALARMCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2LineAlarmConfTemplateTable_entry* table_row = xdsl2LineAlarmConfTemplateTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request, SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2LineAlarmConfTemplateTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2LALARMCONFTEMPROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2LineAlarmConfTemplateTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
