/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINEINVENTORYTABLE_H
#define XDSL2LINEINVENTORYTABLE_H

#define MAX_LEN_8 8
#define MAX_LEN_16 16
#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineInventoryTable(void);
void initialize_table_xdsl2LineInventoryTable(void);
Netsnmp_Node_Handler xdsl2LineInventoryTable_handler;
Netsnmp_First_Data_Point  xdsl2LineInventoryTable_get_first_data_point;
static void populate_xdsl2LineInventoryTable(void);
Netsnmp_Next_Data_Point   xdsl2LineInventoryTable_get_next_data_point;

/* column number definitions for table xdsl2LineInventoryTable */
       #define COLUMN_XDSL2LINVUNIT		1
       #define COLUMN_XDSL2LINVG994VENDORID		2
       #define COLUMN_XDSL2LINVSYSTEMVENDORID		3
       #define COLUMN_XDSL2LINVVERSIONNUMBER		4
       #define COLUMN_XDSL2LINVSERIALNUMBER		5
       #define COLUMN_XDSL2LINVSELFTESTRESULT		6
       #define COLUMN_XDSL2LINVTRANSMISSIONCAPABILITIES		7
#endif /* XDSL2LINEINVENTORYTABLE_H */
