/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINEBANDTABLE_H
#define XDSL2LINEBANDTABLE_H

/* function declarations */
void init_xdsl2LineBandTable(void);
void initialize_table_xdsl2LineBandTable(void);
Netsnmp_Node_Handler xdsl2LineBandTable_handler;
Netsnmp_First_Data_Point  xdsl2LineBandTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineBandTable_get_next_data_point;

/* column number definitions for table xdsl2LineBandTable */
       #define COLUMN_XDSL2LINEBAND		1
       #define COLUMN_XDSL2LINEBANDSTATUSLNATTEN		2
       #define COLUMN_XDSL2LINEBANDSTATUSSIGATTEN		3
       #define COLUMN_XDSL2LINEBANDSTATUSSNRMARGIN		4
#endif /* XDSL2LINEBANDTABLE_H */
