/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2LINEALARMCONFTEMPLATETABLE_H
#define XDSL2LINEALARMCONFTEMPLATETABLE_H

#define MAX_LEN_32 32

/* function declarations */
void init_xdsl2LineAlarmConfTemplateTable(void);
void initialize_table_xdsl2LineAlarmConfTemplateTable(void);
Netsnmp_Node_Handler xdsl2LineAlarmConfTemplateTable_handler;
Netsnmp_First_Data_Point  xdsl2LineAlarmConfTemplateTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2LineAlarmConfTemplateTable_get_next_data_point;

/* column number definitions for table xdsl2LineAlarmConfTemplateTable */
       #define COLUMN_XDSL2LALARMCONFTEMPTEMPLATENAME		1
       #define COLUMN_XDSL2LALARMCONFTEMPLINEPROFILE		2
       #define COLUMN_XDSL2LALARMCONFTEMPCHAN1CONFPROFILE		3
       #define COLUMN_XDSL2LALARMCONFTEMPCHAN2CONFPROFILE		4
       #define COLUMN_XDSL2LALARMCONFTEMPCHAN3CONFPROFILE		5
       #define COLUMN_XDSL2LALARMCONFTEMPCHAN4CONFPROFILE		6
       #define COLUMN_XDSL2LALARMCONFTEMPROWSTATUS		7
#endif /* XDSL2LINEALARMCONFTEMPLATETABLE_H */
