/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef XDSL2PMCHHIST15MINTABLE_H
#define XDSL2PMCHHIST15MINTABLE_H

/* function declarations */
void init_xdsl2PMChHist15MinTable(void);
void initialize_table_xdsl2PMChHist15MinTable(void);
Netsnmp_Node_Handler xdsl2PMChHist15MinTable_handler;
Netsnmp_First_Data_Point  xdsl2PMChHist15MinTable_get_first_data_point;
Netsnmp_Next_Data_Point   xdsl2PMChHist15MinTable_get_next_data_point;

/* column number definitions for table xdsl2PMChHist15MinTable */
       #define COLUMN_XDSL2PMCHHIST15MUNIT		1
       #define COLUMN_XDSL2PMCHHIST15MINTERVAL		2
       #define COLUMN_XDSL2PMCHHIST15MMONITOREDTIME		3
       #define COLUMN_XDSL2PMCHHIST15MCODINGVIOLATIONS		4
       #define COLUMN_XDSL2PMCHHIST15MCORRECTEDBLOCKS		5
       #define COLUMN_XDSL2PMCHHIST15MVALIDINTERVAL		6
#endif /* XDSL2PMCHHIST15MINTABLE_H */
