/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xdsl2ChConfProfileTable.h"

 /** Initializes the xdsl2ChConfProfileTable module */
void
init_xdsl2ChConfProfileTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
	initialize_table_xdsl2ChConfProfileTable();
}


/** Initialize the xdsl2ChConfProfileTable table by defining its contents and how it's structured */
void
initialize_table_xdsl2ChConfProfileTable(void)
{
	const oid xdsl2ChConfProfileTable_oid[] = { 1,3,6,1,2,1,10,251,1,5,2,1 };
	const size_t xdsl2ChConfProfileTable_oid_len = OID_LENGTH(xdsl2ChConfProfileTable_oid);
	netsnmp_handler_registration* reg;
	netsnmp_iterator_info* iinfo;
	netsnmp_table_registration_info* table_info;

	DEBUGMSGTL(("xdsl2ChConfProfileTable:init", "initializing table xdsl2ChConfProfileTable\n"));

	reg = netsnmp_create_handler_registration(
		"xdsl2ChConfProfileTable", xdsl2ChConfProfileTable_handler,
		xdsl2ChConfProfileTable_oid, xdsl2ChConfProfileTable_oid_len,
		HANDLER_CAN_RWRITE
	);

	table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	netsnmp_table_helper_add_indexes(table_info,
		ASN_OCTET_STR,  /* index: xdsl2ChConfProfProfileName */
		0);
	table_info->min_column = COLUMN_XDSL2CHCONFPROFMINDATARATEDS;
	table_info->max_column = COLUMN_XDSL2CHCONFPROFROWSTATUS;

	iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	iinfo->get_first_data_point = xdsl2ChConfProfileTable_get_first_data_point;
	iinfo->get_next_data_point = xdsl2ChConfProfileTable_get_next_data_point;
	iinfo->table_reginfo = table_info;

	netsnmp_register_table_iterator(reg, iinfo);

	/* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct xdsl2ChConfProfileTable_entry {
	/* Index values */
	char xdsl2ChConfProfProfileName[MAX_PROFILE_NAME_LEN];
	size_t xdsl2ChConfProfProfileName_len;

	/* Column values */
	u_long xdsl2ChConfProfMinDataRateDs;
	u_long old_xdsl2ChConfProfMinDataRateDs;
	u_long xdsl2ChConfProfMinDataRateUs;
	u_long old_xdsl2ChConfProfMinDataRateUs;
	u_long xdsl2ChConfProfMinResDataRateDs;
	u_long old_xdsl2ChConfProfMinResDataRateDs;
	u_long xdsl2ChConfProfMinResDataRateUs;
	u_long old_xdsl2ChConfProfMinResDataRateUs;
	u_long xdsl2ChConfProfMaxDataRateDs;
	u_long old_xdsl2ChConfProfMaxDataRateDs;
	u_long xdsl2ChConfProfMaxDataRateUs;
	u_long old_xdsl2ChConfProfMaxDataRateUs;
	u_long xdsl2ChConfProfMinDataRateLowPwrDs;
	u_long old_xdsl2ChConfProfMinDataRateLowPwrDs;
	u_long xdsl2ChConfProfMinDataRateLowPwrUs;
	u_long old_xdsl2ChConfProfMinDataRateLowPwrUs;
	u_long xdsl2ChConfProfMaxDelayDs;
	u_long old_xdsl2ChConfProfMaxDelayDs;
	u_long xdsl2ChConfProfMaxDelayUs;
	u_long old_xdsl2ChConfProfMaxDelayUs;
	long xdsl2ChConfProfMinProtectionDs;
	long old_xdsl2ChConfProfMinProtectionDs;
	long xdsl2ChConfProfMinProtectionUs;
	long old_xdsl2ChConfProfMinProtectionUs;
	long xdsl2ChConfProfMinProtection8Ds;
	long old_xdsl2ChConfProfMinProtection8Ds;
	long xdsl2ChConfProfMinProtection8Us;
	long old_xdsl2ChConfProfMinProtection8Us;
	long xdsl2ChConfProfMaxBerDs;
	long old_xdsl2ChConfProfMaxBerDs;
	long xdsl2ChConfProfMaxBerUs;
	long old_xdsl2ChConfProfMaxBerUs;
	u_long xdsl2ChConfProfUsDataRateDs;
	u_long old_xdsl2ChConfProfUsDataRateDs;
	u_long xdsl2ChConfProfDsDataRateDs;
	u_long old_xdsl2ChConfProfDsDataRateDs;
	u_long xdsl2ChConfProfUsDataRateUs;
	u_long old_xdsl2ChConfProfUsDataRateUs;
	u_long xdsl2ChConfProfDsDataRateUs;
	u_long old_xdsl2ChConfProfDsDataRateUs;
	long xdsl2ChConfProfImaEnabled;
	long old_xdsl2ChConfProfImaEnabled;
	u_long xdsl2ChConfProfMaxDelayVar;
	u_long old_xdsl2ChConfProfMaxDelayVar;
	long xdsl2ChConfProfInitPolicy;
	long old_xdsl2ChConfProfInitPolicy;
	long xdsl2ChConfProfRowStatus;

	/* Illustrate using a simple linked list */
	int   valid;
	struct xdsl2ChConfProfileTable_entry* next;
};

struct xdsl2ChConfProfileTable_entry* xdsl2ChConfProfileTable_head;

/* create a new row in the (unsorted) table */
struct xdsl2ChConfProfileTable_entry*
	xdsl2ChConfProfileTable_createEntry(
		unsigned char* xdsl2ChConfProfProfileName,
		size_t xdsl2ChConfProfProfileName_len) {
	struct xdsl2ChConfProfileTable_entry* entry;

	entry = SNMP_MALLOC_TYPEDEF(struct xdsl2ChConfProfileTable_entry);
	if (!entry)
		return NULL;

	memcpy(entry->xdsl2ChConfProfProfileName, xdsl2ChConfProfProfileName, xdsl2ChConfProfProfileName_len);
	entry->xdsl2ChConfProfProfileName_len = xdsl2ChConfProfProfileName_len;
	entry->next = xdsl2ChConfProfileTable_head;
	xdsl2ChConfProfileTable_head = entry;
	return entry;
}

/* remove a row from the table */
void
xdsl2ChConfProfileTable_removeEntry(struct xdsl2ChConfProfileTable_entry* entry) {
	struct xdsl2ChConfProfileTable_entry* ptr, * prev;

	if (!entry)
		return;    /* Nothing to remove */

	for (ptr = xdsl2ChConfProfileTable_head, prev = NULL;
		ptr != NULL;
		prev = ptr, ptr = ptr->next) {
		if (ptr == entry)
			break;
	}
	if (!ptr)
		return;    /* Can't find it */

	if (prev == NULL)
		xdsl2ChConfProfileTable_head = ptr->next;
	else
		prev->next = ptr->next;

	SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list*
xdsl2ChConfProfileTable_get_first_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	*my_loop_context = xdsl2ChConfProfileTable_head;
	return xdsl2ChConfProfileTable_get_next_data_point(my_loop_context, my_data_context,
		put_index_data, mydata);
}

netsnmp_variable_list*
xdsl2ChConfProfileTable_get_next_data_point(void** my_loop_context,
	void** my_data_context,
	netsnmp_variable_list* put_index_data,
	netsnmp_iterator_info* mydata)
{
	struct xdsl2ChConfProfileTable_entry* entry = (struct xdsl2ChConfProfileTable_entry*)*my_loop_context;
	netsnmp_variable_list* idx = put_index_data;

	if (entry) {
		snmp_set_var_value(idx, entry->xdsl2ChConfProfProfileName, sizeof(entry->xdsl2ChConfProfProfileName));
		idx = idx->next_variable;
		*my_data_context = (void*)entry;
		*my_loop_context = (void*)entry->next;
		return put_index_data;
	}
	else {
		return NULL;
	}
}


/** handles requests for the xdsl2ChConfProfileTable table */
int
xdsl2ChConfProfileTable_handler(
	netsnmp_mib_handler* handler,
	netsnmp_handler_registration* reginfo,
	netsnmp_agent_request_info* reqinfo,
	netsnmp_request_info* requests) {

	netsnmp_request_info* request;
	netsnmp_table_request_info* table_info;
	struct xdsl2ChConfProfileTable_entry* table_entry;

	DEBUGMSGTL(("xdsl2ChConfProfileTable:handler", "Processing request (%d)\n", reqinfo->mode));

	switch (reqinfo->mode) {
		/*
		 * Read-support (also covers GetNext requests)
		 */
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFMINDATARATEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinDataRateDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinDataRateUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinResDataRateDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinResDataRateUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMaxDataRateDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMaxDataRateUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinDataRateLowPwrDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMinDataRateLowPwrUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMaxDelayDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMaxDelayUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMinProtectionDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMinProtectionUs);
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8DS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMinProtection8Ds);
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8US:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMinProtection8Us);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMaxBerDs);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfMaxBerUs);
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfUsDataRateDs);
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEDS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfDsDataRateDs);
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfUsDataRateUs);
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfDsDataRateUs);
				break;
			case COLUMN_XDSL2CHCONFPROFIMAENABLED:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfImaEnabled);
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYVAR:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
					table_entry->xdsl2ChConfProfMaxDelayVar);
				break;
			case COLUMN_XDSL2CHCONFPROFINITPOLICY:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfInitPolicy);
				break;
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				if (!table_entry) {
					netsnmp_set_request_error(reqinfo, request,
						SNMP_NOSUCHINSTANCE);
					continue;
				}
				snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
					table_entry->xdsl2ChConfProfRowStatus);
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

		/*
		 * Write-support
		 */
	case MODE_SET_RESERVE1:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);
			int ret;
			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFMINDATARATEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8DS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8US:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEDS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEUS:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFIMAENABLED:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYVAR:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFINITPOLICY:
				/* or possibly 'netsnmp_check_vb_int_range' */
				ret = netsnmp_check_vb_int(request->requestvb);
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				ret = netsnmp_check_vb_rowstatus(request->requestvb,
					(table_entry ? RS_ACTIVE : RS_NONEXISTENT));
				if (ret != SNMP_ERR_NOERROR) {
					netsnmp_set_request_error(reqinfo, request, ret);
					return SNMP_ERR_NOERROR;
				}
				break;
			default:
				netsnmp_set_request_error(reqinfo, request,
					SNMP_ERR_NOTWRITABLE);
				return SNMP_ERR_NOERROR;
			}
		}
		break;

	case MODE_SET_RESERVE2:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					struct xdsl2ChConfProfileTable_entry* table_row = xdsl2ChConfProfileTable_createEntry(table_info->indexes->val.string, table_info->indexes->val_len);
					if (table_row) {
						netsnmp_insert_iterator_context(request, table_row);
					}
					else {
						netsnmp_set_request_error(reqinfo, request,
							SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}
				}
			}
		}
		break;

	case MODE_SET_FREE:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2ChConfProfileTable_removeEntry(table_entry);
					}
				}
			}
		}
		break;

	case MODE_SET_ACTION:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFMINDATARATEDS:
				table_entry->old_xdsl2ChConfProfMinDataRateDs = table_entry->xdsl2ChConfProfMinDataRateDs;
				table_entry->xdsl2ChConfProfMinDataRateDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATEUS:
				table_entry->old_xdsl2ChConfProfMinDataRateUs = table_entry->xdsl2ChConfProfMinDataRateUs;
				table_entry->xdsl2ChConfProfMinDataRateUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEDS:
				table_entry->old_xdsl2ChConfProfMinResDataRateDs = table_entry->xdsl2ChConfProfMinResDataRateDs;
				table_entry->xdsl2ChConfProfMinResDataRateDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEUS:
				table_entry->old_xdsl2ChConfProfMinResDataRateUs = table_entry->xdsl2ChConfProfMinResDataRateUs;
				table_entry->xdsl2ChConfProfMinResDataRateUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEDS:
				table_entry->old_xdsl2ChConfProfMaxDataRateDs = table_entry->xdsl2ChConfProfMaxDataRateDs;
				table_entry->xdsl2ChConfProfMaxDataRateDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEUS:
				table_entry->old_xdsl2ChConfProfMaxDataRateUs = table_entry->xdsl2ChConfProfMaxDataRateUs;
				table_entry->xdsl2ChConfProfMaxDataRateUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRDS:
				table_entry->old_xdsl2ChConfProfMinDataRateLowPwrDs = table_entry->xdsl2ChConfProfMinDataRateLowPwrDs;
				table_entry->xdsl2ChConfProfMinDataRateLowPwrDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRUS:
				table_entry->old_xdsl2ChConfProfMinDataRateLowPwrUs = table_entry->xdsl2ChConfProfMinDataRateLowPwrUs;
				table_entry->xdsl2ChConfProfMinDataRateLowPwrUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYDS:
				table_entry->old_xdsl2ChConfProfMaxDelayDs = table_entry->xdsl2ChConfProfMaxDelayDs;
				table_entry->xdsl2ChConfProfMaxDelayDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYUS:
				table_entry->old_xdsl2ChConfProfMaxDelayUs = table_entry->xdsl2ChConfProfMaxDelayUs;
				table_entry->xdsl2ChConfProfMaxDelayUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONDS:
				table_entry->old_xdsl2ChConfProfMinProtectionDs = table_entry->xdsl2ChConfProfMinProtectionDs;
				table_entry->xdsl2ChConfProfMinProtectionDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONUS:
				table_entry->old_xdsl2ChConfProfMinProtectionUs = table_entry->xdsl2ChConfProfMinProtectionUs;
				table_entry->xdsl2ChConfProfMinProtectionUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8DS:
				table_entry->old_xdsl2ChConfProfMinProtection8Ds = table_entry->xdsl2ChConfProfMinProtection8Ds;
				table_entry->xdsl2ChConfProfMinProtection8Ds = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8US:
				table_entry->old_xdsl2ChConfProfMinProtection8Us = table_entry->xdsl2ChConfProfMinProtection8Us;
				table_entry->xdsl2ChConfProfMinProtection8Us = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERDS:
				table_entry->old_xdsl2ChConfProfMaxBerDs = table_entry->xdsl2ChConfProfMaxBerDs;
				table_entry->xdsl2ChConfProfMaxBerDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERUS:
				table_entry->old_xdsl2ChConfProfMaxBerUs = table_entry->xdsl2ChConfProfMaxBerUs;
				table_entry->xdsl2ChConfProfMaxBerUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEDS:
				table_entry->old_xdsl2ChConfProfUsDataRateDs = table_entry->xdsl2ChConfProfUsDataRateDs;
				table_entry->xdsl2ChConfProfUsDataRateDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEDS:
				table_entry->old_xdsl2ChConfProfDsDataRateDs = table_entry->xdsl2ChConfProfDsDataRateDs;
				table_entry->xdsl2ChConfProfDsDataRateDs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEUS:
				table_entry->old_xdsl2ChConfProfUsDataRateUs = table_entry->xdsl2ChConfProfUsDataRateUs;
				table_entry->xdsl2ChConfProfUsDataRateUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEUS:
				table_entry->old_xdsl2ChConfProfDsDataRateUs = table_entry->xdsl2ChConfProfDsDataRateUs;
				table_entry->xdsl2ChConfProfDsDataRateUs = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFIMAENABLED:
				table_entry->old_xdsl2ChConfProfImaEnabled = table_entry->xdsl2ChConfProfImaEnabled;
				table_entry->xdsl2ChConfProfImaEnabled = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYVAR:
				table_entry->old_xdsl2ChConfProfMaxDelayVar = table_entry->xdsl2ChConfProfMaxDelayVar;
				table_entry->xdsl2ChConfProfMaxDelayVar = *request->requestvb->val.integer;
				break;
			case COLUMN_XDSL2CHCONFPROFINITPOLICY:
				table_entry->old_xdsl2ChConfProfInitPolicy = table_entry->xdsl2ChConfProfInitPolicy;
				table_entry->xdsl2ChConfProfInitPolicy = *request->requestvb->val.integer;
				break;
			}
		}
		/* Check the internal consistency of an active row */
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_ACTIVE:
				case RS_CREATEANDGO:
					netsnmp_set_request_error(reqinfo, request,
						SNMP_ERR_INCONSISTENTVALUE);
					return SNMP_ERR_NOERROR;
				}
			}
		}
		break;

	case MODE_SET_UNDO:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFMINDATARATEDS:
				table_entry->xdsl2ChConfProfMinDataRateDs = table_entry->old_xdsl2ChConfProfMinDataRateDs;
				table_entry->old_xdsl2ChConfProfMinDataRateDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATEUS:
				table_entry->xdsl2ChConfProfMinDataRateUs = table_entry->old_xdsl2ChConfProfMinDataRateUs;
				table_entry->old_xdsl2ChConfProfMinDataRateUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEDS:
				table_entry->xdsl2ChConfProfMinResDataRateDs = table_entry->old_xdsl2ChConfProfMinResDataRateDs;
				table_entry->old_xdsl2ChConfProfMinResDataRateDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINRESDATARATEUS:
				table_entry->xdsl2ChConfProfMinResDataRateUs = table_entry->old_xdsl2ChConfProfMinResDataRateUs;
				table_entry->old_xdsl2ChConfProfMinResDataRateUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEDS:
				table_entry->xdsl2ChConfProfMaxDataRateDs = table_entry->old_xdsl2ChConfProfMaxDataRateDs;
				table_entry->old_xdsl2ChConfProfMaxDataRateDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDATARATEUS:
				table_entry->xdsl2ChConfProfMaxDataRateUs = table_entry->old_xdsl2ChConfProfMaxDataRateUs;
				table_entry->old_xdsl2ChConfProfMaxDataRateUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRDS:
				table_entry->xdsl2ChConfProfMinDataRateLowPwrDs = table_entry->old_xdsl2ChConfProfMinDataRateLowPwrDs;
				table_entry->old_xdsl2ChConfProfMinDataRateLowPwrDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINDATARATELOWPWRUS:
				table_entry->xdsl2ChConfProfMinDataRateLowPwrUs = table_entry->old_xdsl2ChConfProfMinDataRateLowPwrUs;
				table_entry->old_xdsl2ChConfProfMinDataRateLowPwrUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYDS:
				table_entry->xdsl2ChConfProfMaxDelayDs = table_entry->old_xdsl2ChConfProfMaxDelayDs;
				table_entry->old_xdsl2ChConfProfMaxDelayDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYUS:
				table_entry->xdsl2ChConfProfMaxDelayUs = table_entry->old_xdsl2ChConfProfMaxDelayUs;
				table_entry->old_xdsl2ChConfProfMaxDelayUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONDS:
				table_entry->xdsl2ChConfProfMinProtectionDs = table_entry->old_xdsl2ChConfProfMinProtectionDs;
				table_entry->old_xdsl2ChConfProfMinProtectionDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTIONUS:
				table_entry->xdsl2ChConfProfMinProtectionUs = table_entry->old_xdsl2ChConfProfMinProtectionUs;
				table_entry->old_xdsl2ChConfProfMinProtectionUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8DS:
				table_entry->xdsl2ChConfProfMinProtection8Ds = table_entry->old_xdsl2ChConfProfMinProtection8Ds;
				table_entry->old_xdsl2ChConfProfMinProtection8Ds = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMINPROTECTION8US:
				table_entry->xdsl2ChConfProfMinProtection8Us = table_entry->old_xdsl2ChConfProfMinProtection8Us;
				table_entry->old_xdsl2ChConfProfMinProtection8Us = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERDS:
				table_entry->xdsl2ChConfProfMaxBerDs = table_entry->old_xdsl2ChConfProfMaxBerDs;
				table_entry->old_xdsl2ChConfProfMaxBerDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXBERUS:
				table_entry->xdsl2ChConfProfMaxBerUs = table_entry->old_xdsl2ChConfProfMaxBerUs;
				table_entry->old_xdsl2ChConfProfMaxBerUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEDS:
				table_entry->xdsl2ChConfProfUsDataRateDs = table_entry->old_xdsl2ChConfProfUsDataRateDs;
				table_entry->old_xdsl2ChConfProfUsDataRateDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEDS:
				table_entry->xdsl2ChConfProfDsDataRateDs = table_entry->old_xdsl2ChConfProfDsDataRateDs;
				table_entry->old_xdsl2ChConfProfDsDataRateDs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFUSDATARATEUS:
				table_entry->xdsl2ChConfProfUsDataRateUs = table_entry->old_xdsl2ChConfProfUsDataRateUs;
				table_entry->old_xdsl2ChConfProfUsDataRateUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFDSDATARATEUS:
				table_entry->xdsl2ChConfProfDsDataRateUs = table_entry->old_xdsl2ChConfProfDsDataRateUs;
				table_entry->old_xdsl2ChConfProfDsDataRateUs = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFIMAENABLED:
				table_entry->xdsl2ChConfProfImaEnabled = table_entry->old_xdsl2ChConfProfImaEnabled;
				table_entry->old_xdsl2ChConfProfImaEnabled = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFMAXDELAYVAR:
				table_entry->xdsl2ChConfProfMaxDelayVar = table_entry->old_xdsl2ChConfProfMaxDelayVar;
				table_entry->old_xdsl2ChConfProfMaxDelayVar = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFINITPOLICY:
				table_entry->xdsl2ChConfProfInitPolicy = table_entry->old_xdsl2ChConfProfInitPolicy;
				table_entry->old_xdsl2ChConfProfInitPolicy = 0;
				break;
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
				case RS_CREATEANDWAIT:
					if (table_entry && !table_entry->valid) {
						xdsl2ChConfProfileTable_removeEntry(table_entry);
					}
				}
				break;
			}
		}
		break;

	case MODE_SET_COMMIT:
		for (request = requests; request; request = request->next) {
			table_entry = (struct xdsl2ChConfProfileTable_entry*)
				netsnmp_extract_iterator_context(request);
			table_info = netsnmp_extract_table_info(request);

			switch (table_info->colnum) {
			case COLUMN_XDSL2CHCONFPROFROWSTATUS:
				switch (*request->requestvb->val.integer) {
				case RS_CREATEANDGO:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_ACTIVE:
					table_entry->xdsl2ChConfProfRowStatus = RS_ACTIVE;
					break;

				case RS_CREATEANDWAIT:
					table_entry->valid = 1;
					/* Fall-through */
				case RS_NOTINSERVICE:
					table_entry->xdsl2ChConfProfRowStatus = RS_NOTINSERVICE;
					break;

				case RS_DESTROY:
					xdsl2ChConfProfileTable_removeEntry(table_entry);
				}
			}
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}
